import test from 'node:test';import assert from 'node:assert/strict';
import {PurchaseJob,createPurchaseRecord,TASK_KEY} from '../web/checkout-connector/job.js';
import {PRO_PLAN,proDigest} from '../src/desktop/browser-session.mjs';
import {AuthContinuation} from '../src/desktop/auth-continuation.mjs';
async function lateCheckout(window=1800000){let now=0,seq=0,sentAt=null,row={...createPurchaseRecord(PRO_PLAN,{taskId:'FAKE-wait',planDigest:proDigest,tabId:7,now:0,id:()=>crypto.randomUUID()}),expiresAt:window};const actions=[],deadlines=[];
 const store={get:async()=>structuredClone(row),put:async(k,v)=>{assert.equal(k,TASK_KEY);row=structuredClone(v);if(row.pending)deadlines.push(row.pending.deadline);}};
 const item={...PRO_PLAN.product,quantity:1,totalCny:9999,itemVerified:true,verified:false,store:null,fulfillment:null};
 const port={observe:async()=>({schema:'applebuy-merchant-read/v1',documentId:'FAKE-doc',seq:++seq,phase:sentAt===null?'BAG':now<12000?'PROCESSING':'AUTH',verifiedStep:sentAt===null,purchase:item,extras:false}),act:async c=>{actions.push(c.action);sentAt=now;return {delivered:true};},wait:async ms=>{now+=ms;}};
 await new PurchaseJob({store,port,now:()=>now,transitionMs:60000,maxWaitMs:60000}).run(PRO_PLAN,{tabId:7,planDigest:proDigest});return {row,actions,deadlines,now};
}
test('C212 ordinary successor later than eight seconds gets readonly settling and no repeated Checkout',async()=>{const x=await lateCheckout();assert.ok(x.now>=12000);assert.equal(x.row.lastPhase,'AUTH');assert.deepEqual(x.actions,['checkout']);assert.ok(x.deadlines.every(d=>d===60000));assert.equal(x.row.pending.action,'checkout');});
test('C212 longer settling never changes or outlives the original task authority window',async()=>{const x=await lateCheckout(9000);assert.equal(x.row.state,'EXPIRED');assert.equal(x.row.expiresAt,9000);assert.ok(x.deadlines.every(d=>d===9000));assert.deepEqual(x.actions,['checkout']);});
test('C212 continuation watcher respects the original window and does not turn merchant errors into a resume',async()=>{let now=0,callback,stopped=0,resumes=0;const watch=new AuthContinuation({observe:async()=>({phase:'REVIEW',merchantError:true}),now:()=>now,setTimer:f=>(callback=f,1),clearTimer:()=>{},onStopped:()=>stopped++});watch.start(()=>resumes++,{phases:['REVIEW'],deadline:100});await callback();assert.equal(resumes,0);assert.equal(stopped,1);watch.start(()=>resumes++,{phases:['REVIEW'],deadline:100});now=101;await callback();assert.equal(resumes,0);assert.equal(stopped,2);});
test('C212 watcher waits through unknown/auth and resumes once only on its expected successor',async()=>{let callback,resumes=0,phase='UNKNOWN';const watch=new AuthContinuation({observe:async()=>({phase}),now:()=>0,setTimer:f=>(callback=f,1),clearTimer:()=>{}});watch.start(()=>resumes++,{phases:['PAYMENT'],deadline:1000});await callback();phase='AUTH';await callback();phase='PAYMENT';await callback();await callback();assert.equal(resumes,1);assert.equal(watch.timer,null);});
