// Local native DOM and production receiver/controller; all locations/approval/ledger facts FAKE.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {createRequire} from 'node:module';import {homedir} from 'node:os';import {join} from 'node:path';
import {merchantDocument} from '../web/checkout-connector/page-program.js';import {PRO_PLAN,proDigest} from '../src/desktop/browser-session.mjs';
import * as rpc from '../web/checkout-connector/checkout-rpc-contract.js';import {CheckoutRpcPeer} from '../web/checkout-connector/checkout-rpc-peer.js';
import {ChromePort} from '../web/checkout-connector/chrome-port.js';import {PurchaseJob,createPurchaseRecord,TASK_KEY} from '../web/checkout-connector/job.js';
const EXP='https://www.apple.com.cn/shop/sorry/session_expired';
test('C184 expiry blocks a matching command and stale prior navigation authorisation before script or update',async()=>{let scripts=0,updates=0;const page={schema:'applebuy-merchant-read/v1',phase:'UNKNOWN',path:'/shop/sorry/session_expired',merchantError:'session-expired'};const api={permissions:{contains:async()=>true},tabs:{get:async()=>({id:7,url:EXP,status:'complete'}),update:async()=>{updates++;}},scripting:{executeScript:async()=>{scripts++;return [];}}};const peer=new CheckoutRpcPeer({api,contextId:'FAKE-c184-context',purchaseAllowed:true});peer.tabs.set(7,{last:{documentId:'FAKE-expired',page},navigation:rpc.BAG});await assert.rejects(peer.operation('updateTab',{tabId:7,url:rpc.BAG}));await assert.rejects(peer.operation('merchantDocument',{tabId:7,plan:PRO_PLAN,documentId:'FAKE-expired',command:{action:'checkout',id:'FAKE-valid-id',taskId:'FAKE-task',documentId:'FAKE-expired',expected:JSON.stringify(page),authorized:true,structured:true}}));assert.equal(scripts,0);assert.equal(updates,0);});
const {chromium}=createRequire(import.meta.url)(join(homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
let browser,server,origin;
before(async()=>{server=http.createServer((q,r)=>r.end('<!doctype html><body>FAKE expiry fixture</body>'));await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-background-networking']});});
after(async()=>{await browser?.close();server?.closeAllConnections?.();if(server)await new Promise(r=>server.close(r));});
async function read({url=EXP,html='<main><h1>你的操作已超时。</h1></main>',command=null,memo=false}={}){const c=await browser.newContext({serviceWorkers:'block'});await c.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort('blockedbyclient'));await c.routeWebSocket('**/*',s=>s.close());try{const p=await c.newPage();await p.goto(origin);await p.setContent(html);return await p.evaluate(async({source,url,plan,command,memo})=>{globalThis.__fakeUrl=url;if(memo)globalThis.__applebuyExecuted=new Set([command.id]);for(const e of document.querySelectorAll('input'))Object.defineProperty(e,'value',{get(){throw Error('Private input must not be read');}});const f=(new Function('return '+source.replace('new URL(location.href)','new URL(globalThis.__fakeUrl)')))();return await f(plan,command);},{source:merchantDocument.toString(),url,plan:PRO_PLAN,command,memo});}finally{await c.close();}}
test('C181 known expiry path and visible exact MAIN H1 are a typed observation, not purchase proof',async()=>{const r=await read({html:'<main><h1>你的操作已超时。</h1><input type=password value=FAKE-private></main>'});assert.equal(r.merchantError,'session-expired');assert.equal(r.phase,'UNKNOWN');assert.equal(r.verifiedStep,false);assert.equal(r.reason,'merchant-session-expired');assert.equal(r.purchase,undefined);assert.equal(JSON.stringify(r).includes('FAKE-private'),false);});
for(const [name,options]of [['hidden',{html:'<main><h1 hidden>你的操作已超时。</h1></main>'}],['duplicate',{html:'<main><h1>你的操作已超时。</h1><h1>你的操作已超时。</h1></main>'}],['wrong heading',{html:'<main><h1>暂时无法处理</h1></main>'}],['no main',{html:'<h1>你的操作已超时。</h1>'}],['foreign',{url:'https://www.example.invalid/shop/sorry/session_expired'}],['HTTP',{url:'http://www.apple.com.cn/shop/sorry/session_expired'}],['wrong path',{url:'https://www.apple.com.cn/shop/sorry/other'}]])test('C181 '+name+' cannot claim merchant expiry',async()=>assert.notEqual((await read(options)).merchantError,'session-expired'));
test('C181 no command on an expiry page and no contradictory untouched report after prior delivery',async()=>{const command={action:'submitOrder',id:'FAKE-once',structured:true};const r=await read({command});assert.equal(r.delivered,false);assert.equal(r.touched,false);assert.equal(r.reason,'MerchantSessionExpired');const old=await read({command,memo:true});assert.equal(old.delivered,false);assert.equal(old.touched,true);assert.equal(old.reason,'OperationAlreadyDelivered');});
test('C181 native observation accepts own expiry; navigation and commands do not acquire permission from it',async()=>{assert.equal(rpc.checkoutUrl(EXP),false);assert.equal(typeof rpc.checkoutObservedUrl,'function');assert.equal(rpc.checkoutObservedUrl(EXP),true);let nav=0;const api={permissions:{contains:async()=>true},tabs:{create:async()=>({id:7,status:'complete'}),get:async()=>({id:7,url:EXP,status:'complete'}),update:async()=>{nav++;}},scripting:{executeScript:async()=>[{frameId:0,documentId:'FAKE-expired',result:{schema:'applebuy-merchant-read/v1',phase:'UNKNOWN',verifiedStep:false,path:'/shop/sorry/session_expired',merchantError:'session-expired',reason:'merchant-session-expired'}}]}};const peer=new CheckoutRpcPeer({api,contextId:'FAKE-c181-context',purchaseAllowed:true});await peer.operation('createTab',{url:rpc.BAG});const own=await peer.operation('getTab',{tabId:7});assert.equal(own.url,EXP);const r=await peer.operation('merchantDocument',{tabId:7,plan:PRO_PLAN});assert.equal(r[0].result.merchantError,'session-expired');await assert.rejects(peer.operation('updateTab',{tabId:7,url:EXP}));await assert.rejects(peer.operation('merchantDocument',{tabId:7,plan:PRO_PLAN,documentId:'FAKE-expired',command:{action:'checkout',id:'FAKE-command',taskId:'FAKE-task',documentId:'FAKE-expired',expected:'{}',authorized:true,structured:true}}));assert.equal(nav,0);});
for(const action of ['checkout','chooseSlot','submitOrder'])test('C181 production controller preserves '+action+' and sends zero actions on expiry',async()=>{let row={...createPurchaseRecord(PRO_PLAN,{taskId:'FAKE-c181',planDigest:proDigest,tabId:7,now:Date.now(),id:()=> 'FAKE'}),pending:{action,id:'FAKE-pending',documentId:'FAKE-old',beforePhase:'BAG',deadline:Date.now()+60000}};if(action==='submitOrder')row.finalIntent={id:'FAKE-pending',sent:true};const pending=structuredClone(row.pending),final=structuredClone(row.finalIntent);let sent=0;const store={get:async()=>structuredClone(row),put:async(k,v)=>{assert.equal(k,TASK_KEY);row=structuredClone(v);}};const api={permissions:{contains:async()=>true},tabs:{get:async()=>({id:7,url:EXP})},scripting:{executeScript:async()=>[{frameId:0,documentId:'FAKE-expired',result:{schema:'applebuy-merchant-read/v1',phase:'UNKNOWN',verifiedStep:false,path:'/shop/sorry/session_expired',merchantError:'session-expired',reason:'merchant-session-expired'}}]}};const port=new ChromePort(api,7,{authorized:true,mode:'purchase'});port.act=async()=>{sent++;throw Error('No action on expiry');};await new PurchaseJob({store,port}).run(PRO_PLAN,{tabId:7,planDigest:proDigest});assert.deepEqual(row.pending,pending);assert.deepEqual(row.finalIntent,final);assert.equal(sent,0);if(action!=='submitOrder')assert.equal(row.reason,'merchant-session-expired; existing intent preserved; no automatic repeat');});
