// Observed receipt structure rendered in an isolated local Chrome. All data and transport are FAKE.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {createRequire} from 'node:module';import {homedir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {merchantDocument} from '../web/checkout-connector/page-program.js';import {ChromePort,allowedMerchantUrl,allowedMerchantObservationUrl} from '../web/checkout-connector/chrome-port.js';
import {checkoutUrl,checkoutObservedUrl} from '../web/checkout-connector/checkout-rpc-contract.js';import {CheckoutRpcPeer} from '../web/checkout-connector/checkout-rpc-peer.js';
import {NativeCheckoutApi} from '../src/desktop/native-checkout-api.mjs';import {DesktopCheckoutRuntime} from '../src/desktop/checkout-runtime.mjs';
import {createPurchaseRecord,TASK_KEY} from '../web/checkout-connector/job.js';import {PRO_PLAN,proDigest} from '../src/desktop/browser-session.mjs';
const {chromium}=createRequire(import.meta.url)(join(homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const url='https://secure10.www.apple.com.cn/shop/checkout/interstitial?_s=FAKE',reference='W123456789012',hash=createHash('sha256').update(reference).digest('hex');let server,browser,origin;
before(async()=>{server=http.createServer((q,r)=>r.end('FAKE C236'));await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-background-networking']});});
after(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));});
async function world(){const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort('blockedbyclient'));await context.routeWebSocket('**/*',s=>s.close());const page=await context.newPage();page.setDefaultTimeout(4000);await page.goto(origin);await page.setContent('<main><h1>你的订单正在等待付款。</h1><h2>iPhone 18 Pro 256GB 黑色</h2><a id="pay">现在支付</a><a data-autom="order-number" href="https://www.apple.com.cn/xc/cn/vieworder/'+reference+'/FAKE@example.invalid">订单 #'+reference+'</a></main>');
 await page.evaluate(()=>{document.documentElement.dataset.fakeClicks='0';document.querySelector('main').addEventListener('click',()=>document.documentElement.dataset.fakeClicks=String(Number(document.documentElement.dataset.fakeClicks)+1));});
 const read=(command=null)=>page.evaluate(({source,plan,url,command})=>new Function('location','return ('+source+')')({href:url})(plan,command),{source:merchantDocument.toString(),plan:PRO_PLAN,url,command});return {context,page,read};}
test('C236 receipt path is observation/removal only, not a navigation or purchase address',()=>{assert.equal(allowedMerchantUrl(url),false);assert.equal(checkoutUrl(url),false);assert.equal(allowedMerchantObservationUrl(url),true);assert.equal(checkoutObservedUrl(url),true);for(const u of ['https://evil.invalid/shop/checkout/interstitial','https://secure10.www.apple.com.cn:444/shop/checkout/interstitial','https://u:p@secure10.www.apple.com.cn/shop/checkout/interstitial'])assert.equal(checkoutObservedUrl(u),false);});
test('C236 native receipt hashes only its displayed reference; customer URL and missing detail facts never leave the page',async()=>{const w=await world();try{const o=await w.read();assert.equal(o.phase,'ORDER_RECEIPT');assert.equal(o.orderRefHash,hash);assert.equal(o.receiptAwaitingPayment,true);assert.equal(o.receiptVerified,false);for(const k of ['quantity','totalCny','store','fulfillment'])assert.equal(o.purchase[k],null);assert.equal(JSON.stringify(o).includes('FAKE@example.invalid'),false);assert.equal(JSON.stringify(o).includes(reference),false);assert.equal(o.orderDetailLink,undefined);assert.equal(await w.page.evaluate(()=>document.documentElement.dataset.fakeClicks),'0');}finally{await w.context.close();}});
for(const [name,edit]of [['wrong heading',()=>document.querySelector('h1').textContent='FAKE completed'],['wrong SKU',()=>document.querySelector('h2').textContent='iPhone 18 Pro 512GB 黑色'],['duplicate product',()=>document.querySelector('h2').after(document.querySelector('h2').cloneNode(true))],['duplicate reference',()=>document.querySelector('a[data-autom]').after(document.querySelector('a[data-autom]').cloneNode(true))],['hidden reference',()=>document.querySelector('a[data-autom]').hidden=true],['foreign target',()=>document.querySelector('a[data-autom]').href='https://evil.invalid/xc/cn/vieworder/W123456789012/FAKE@example.invalid'],['different reference',()=>document.querySelector('a[data-autom]').textContent='订单 #W987654321000'],['modal challenge',()=>document.body.insertAdjacentHTML('beforeend','<div role="dialog">FAKE challenge</div>')],['cancellation',()=>document.querySelector('main').insertAdjacentHTML('beforeend','<p>订单已取消</p>')]])test('C236 '+name+' is not a matching unpaid receipt',async()=>{const w=await world();try{await w.page.evaluate(edit);const o=await w.read();assert.equal(o.phase,'UNKNOWN');assert.equal(o.orderRefHash,undefined);}finally{await w.context.close();}});
test('C236 reference changed during hashing fails without a stale reference or click',async()=>{const w=await world();try{await w.page.evaluate(()=>{const digest=crypto.subtle.digest.bind(crypto.subtle);crypto.subtle.digest=async(...a)=>{const r=await digest(...a),link=document.querySelector('a[data-autom]');link.textContent='订单 #W987654321000';link.href='https://www.apple.com.cn/xc/cn/vieworder/W987654321000/FAKE@example.invalid';return r;};});const o=await w.read();assert.equal(o.reason,'receipt-reference-changed');assert.equal(o.orderRefHash,undefined);}finally{await w.context.close();}});
test('C236 no command can click a receipt or payment control',async()=>{const w=await world();try{const r=await w.read({id:'FAKE-submit',structured:true,action:'submitOrder'});assert.equal(r.delivered,false);assert.equal(r.touched,false);assert.equal(r.reason,'ReceiptReadOnly');assert.equal(await w.page.evaluate(()=>document.documentElement.dataset.fakeClicks),'0');}finally{await w.context.close();}});
async function runtimeWorld(executor='desktop',expired=false){const w=await world(),contextId='FAKE-c236-current-owned-context',actions=[];let row={...createPurchaseRecord(PRO_PLAN,{taskId:'FAKE-c236-task',planDigest:proDigest,tabId:7,now:Date.now(),id:()=>crypto.randomUUID()}),desktopContext:contextId,bagAddStarted:true,resourceWritten:true,bagTotalCny:9999,finalIntent:{id:'FAKE-final-intent',sent:true},pending:{id:'FAKE-submit-command',action:'submitOrder',beforePhase:'REVIEW',documentId:'FAKE-review-document',deadline:Date.now()+(expired?-1:60000)}};
 const chrome={locks:{request:async(_n,_o,fn)=>fn({name:'FAKE-owner'})},tabs:{create:async()=>({id:7}),get:async()=>({url,status:'complete'}),remove:async()=>{}},permissions:{contains:async()=>true},scripting:{executeScript:async q=>{if(q.args[1])actions.push(q.args[1].action);return [{frameId:0,documentId:'FAKE-receipt-document',result:await w.read(q.args[1])}];}}};const peer=new CheckoutRpcPeer({api:chrome,contextId,purchaseAllowed:true}),api=new NativeCheckoutApi({contextId,exchange:q=>peer.receive(q)}),store={get:async()=>structuredClone(row),put:async(k,v)=>{assert.equal(k,TASK_KEY);row=structuredClone(v);},acquireOwner:async()=>({owned:true,release:async()=>{}})},runtime=new DesktopCheckoutRuntime({store,executor,launch:async()=>({api,close:()=>api.close()})});
 return {...w,runtime,actions,getRow:()=>row,setHash:h=>row.orderRefHash=h};}
for(const executor of ['desktop','browser'])test('C236 '+executor+' composed runtime preserves one sent final and reports receipt separately from detail verification',async()=>{const w=await runtimeWorld(executor);try{await w.runtime.open();const a=await w.runtime.advance({checkoutApproved:true,newContextConfirmed:true});assert.equal(a.receiptAwaitingPayment,true);assert.equal(a.realOrderVerified,false);assert.equal(w.getRow().orderRefHash,hash);assert.equal(w.getRow().pending.action,'submitOrder');assert.equal(w.getRow().finalIntent.sent,true);const b=await w.runtime.advance({checkoutApproved:true,newContextConfirmed:true});assert.equal(b.receiptAwaitingPayment,true);await assert.rejects(w.runtime.submit({termsAccepted:true,existingOrdersChecked:true,noExtras:true}),/FinalConsent/);assert.deepEqual(w.actions,[]);}finally{await w.runtime.close();await w.context.close();}});
test('C236 another receipt cannot replace a pinned final reference',async()=>{const w=await runtimeWorld();try{w.setHash('a'.repeat(64));await w.runtime.open();const r=await w.runtime.advance({checkoutApproved:true,newContextConfirmed:true});assert.notEqual(r.receiptAwaitingPayment,true);assert.equal(w.getRow().orderRefHash,'a'.repeat(64));assert.deepEqual(w.actions,[]);}finally{await w.runtime.close();await w.context.close();}});
test('C236 late old receipt retains identity but does not announce a fresh awaiting-payment result',async()=>{const w=await runtimeWorld('desktop',true);try{await w.runtime.open();const r=await w.runtime.advance({checkoutApproved:true,newContextConfirmed:true});assert.equal(r.receiptAwaitingPayment,false);assert.equal(w.getRow().orderRefHash,hash);assert.deepEqual(w.actions,[]);}finally{await w.runtime.close();await w.context.close();}});
