// Real isolated Chrome renderer; all merchant endpoints, accounts and orders are FAKE.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {createRequire} from 'node:module';import {homedir} from 'node:os';import {join} from 'node:path';
import {merchantDocument} from '../web/checkout-connector/page-program.js';import {ChromePort} from '../web/checkout-connector/chrome-port.js';
import {PurchaseJob,TASK_KEY,createPurchaseRecord} from '../web/checkout-connector/job.js';
import {PRO_PLAN,proDigest} from '../src/desktop/browser-session.mjs';
import {rowPatch,applyRowPatch} from '../web/checkout-connector/r2-protocol.js';
const {chromium}=createRequire(import.meta.url)(join(homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
let server,browser,origin;
before(async()=>{server=http.createServer((q,r)=>r.end('FAKE C253'));await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-background-networking']});});
after(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));});
const terms='https://www.apple.com.cn/shop/browse/open/salespolicies';
const notice='<div role="alert"><div class="rt-messages"><div class="form-alert is-error"><div class="rt-messages-text">你所选择的“送货与取货”选项已不再为本订单提供。请在下方选择一个新选项。</div></div></div></div>';
const slots='<h1>你希望如何收到订单商品？</h1><button data-autom="companionbar-button">显示订单摘要： RMB 9,999</button><h2>iPhone 18 Pro 256GB 黑色</h2><p>数量 1</p><p>总计 RMB 9,999</p><button role="radio" aria-checked="true">我要取货</button><input type="radio" checked aria-label="Apple 大连恒隆广场"><select aria-label="取货日期"><option>October 10</option><option>October 11</option><option>October 12</option></select><select aria-label="取货时间"><option>可选时段</option><option>21:00 – 21:15</option><option>21:15 – 21:30</option></select><button id="next">继续填写取货详情</button>';
const contact='<h1>FAKE contact</h1><button data-autom="companionbar-button">显示订单摘要： RMB 9,999</button>'+[['姓氏','text'],['名字','text'],['电子邮件地址','email'],['联系人手机号码','tel'],['政府颁发的身份证件号码的后四位','text']].map(([n,t],i)=>`<input type="${t}" aria-label="${n}" required value="${i===2?'FAKE@example.invalid':i===3?'12345678901':i===4?'1234':'FAKE'}" ${i===4?'maxlength="4"':''}>`).join('')+'<button id="details">继续选择付款方式</button>';
const providers=['alipay','wechat','credit','installments0001243254','installments0001864343','installments0001321713','installments0000882476','installments0000833448'];
const payment='<h1>你希望如何付款？</h1><button data-autom="companionbar-button">显示订单摘要： RMB 9,999</button>'+providers.map(k=>{const id='checkout.billing.billingoptions.'+k;return `<input type="radio" name="FAKE-provider" id="${id}" aria-labelledby="${id}_label"><label id="${id}_label" for="${id}"><img alt="${k==='alipay'?'支付宝':k}"></label>`;}).join('')+'<button id="payment" data-autom="continue-button-review">检查订单</button>';
const review='<h1 class="rs-review-header">准备下单了吗？<span>请确保以下信息均准确无误。</span></h1><div class="rs-review-fulfillment"><h2 class="rs-review-shipquote">取货日期待付款完成后确定。</h2><button data-autom="changeShippingMethod">更改零售店</button><h2>iPhone 18 Pro 256GB 黑色</h2><p>数量 1</p><p>总计 RMB 9,999</p></div><div class="rs-review-billing"><h2 class="rs-review-title">付款方式</h2><div class="rs-review-billing-details"><div class="rs-review-billing-cards"><h3 class="rs-review-payment-header"><img class="rs-review-payment-image" alt="支付宝"></h3></div></div></div><a href="'+terms+'">条款和条件</a><button id="final">立即下单</button>';
async function world(){
 const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort('blockedbyclient'));await context.routeWebSocket('**/*',s=>s.close());const page=await context.newPage();await page.goto(origin);await page.setContent('<html data-fake="c253"><body><main id="checkout-container"></main></body></html>');
 await page.evaluate(({slots,notice,contact,payment,review})=>{const main=document.querySelector('main');globalThis.fakeFinals=0;globalThis.fakeOrders=0;globalThis.fakeMode='reject';
  const pickup=()=>{main.innerHTML=(globalThis.fakeFinals?notice:'')+slots;document.getElementById('next').onclick=()=>{main.innerHTML=contact;document.getElementById('details').onclick=()=>{main.innerHTML=payment;document.getElementById('payment').onclick=()=>{main.innerHTML=review;document.getElementById('final').onclick=()=>{globalThis.fakeFinals++;if(globalThis.fakeMode==='reject'&&globalThis.fakeFinals===1)pickup();else if(globalThis.fakeMode==='unknown')main.innerHTML='<h1>FAKE unknown</h1>';else{globalThis.fakeOrders++;document.documentElement.dataset.path='/shop/checkout/interstitial';main.innerHTML='<h1>你的订单正在等待付款。</h1><h2>iPhone 18 Pro 256GB 黑色</h2><a data-autom="order-number" href="https://www.apple.com.cn/xc/cn/vieworder/W123456789/FAKE">订单 #W123456789</a>';}};};};};};pickup();
 },{slots,notice,contact,payment,review});
 const read=(cmd=null)=>page.evaluate(async({source,plan,cmd})=>{if(location.hostname!=='127.0.0.1'||document.documentElement.dataset.fake!=='c253')throw Error('OwnedFixtureOnly');return new Function('location','return ('+source+')')({href:'https://secure10.www.apple.com.cn'+(document.documentElement.dataset.path||'/shop/checkout')})(plan,cmd);},{source:merchantDocument.toString(),plan:PRO_PLAN,cmd});
 const state={row:{...createPurchaseRecord(PRO_PLAN,{taskId:'FAKE-task',planDigest:proDigest,tabId:7,now:Date.now(),id:()=>crypto.randomUUID()}),bagAddStarted:true,resourceWritten:true,bagTotalCny:9999},actions:[],transitions:[]};
 const api={controlledReview:true,sessionId:'FAKE-context',tabs:{get:async()=>({url:'https://secure10.www.apple.com.cn'+(await page.evaluate(()=>document.documentElement.dataset.path||'/shop/checkout')),status:'complete'})},permissions:{contains:async()=>true},scripting:{executeScript:async q=>{if(q.args[1])state.actions.push(q.args[1].action);const result=await read(q.args[1]??null);if(q.args[1]?.action==='submitOrder')await state.afterSubmit?.();return[{frameId:0,documentId:'FAKE-document',result}];}}};
 const store={get:async()=>structuredClone(state.row),put:async(k,r)=>{assert.equal(k,TASK_KEY);const patch=rowPatch(state.row,r);assert.deepEqual(applyRowPatch(state.row,patch),r);state.transitions.push([structuredClone(state.row),structuredClone(r)]);state.row=structuredClone(r);}};
 const run=async consent=>{const port=new ChromePort(api,7,{authorized:true,acceptedSlot:state.row.acceptedSlot,pending:state.row.pending,initialSequence:state.row.lastRead,reviewGrant:consent});const job=new PurchaseJob({store,port,maxSteps:100});return job.run(PRO_PLAN,{tabId:7,planDigest:proDigest,taskId:state.row.taskId,grant:consent});};
 const grant=()=>({id:crypto.randomUUID(),taskId:state.row.taskId,planDigest:proDigest,documentId:'FAKE-document',termsUrl:terms,termsAccepted:true,noExtras:true,existingOrdersChecked:true,expiry:Date.now()+60000,reviewProgressId:state.row.reviewProgress.id});
 return {context,page,read,state,run,grant};
}
test('C253 production renderer+port+job reselect after the explicit final refusal, preserve the first final, and create only one FAKE unpaid order',async()=>{const w=await world();try{
 assert.equal((await w.run()).lastPhase,'REVIEW');let r=await w.run(w.grant());assert.equal(r.lastPhase,'REVIEW',r.reason);assert.equal(r.finalRejections?.length,1);assert.equal(r.acceptedSlot.date,'October 11');assert.equal(await w.page.evaluate(()=>fakeFinals),1);assert.equal(await w.page.evaluate(()=>fakeOrders),0);assert.equal(r.pending,null);
 r=await w.run(w.grant());assert.equal(r.lastPhase,'ORDER_RECEIPT');assert.equal(r.finalIntent.sent,true);assert.equal(await w.page.evaluate(()=>fakeFinals),2);assert.equal(await w.page.evaluate(()=>fakeOrders),1);await w.run();assert.equal(await w.page.evaluate(()=>fakeFinals),2);assert.equal(w.state.actions.filter(x=>x==='chooseSlot').length,2);assert.equal(w.state.actions.includes('addBag'),false);
 const transition=w.state.transitions.find(([a,b])=>(b.finalRejections?.length??0)>(a.finalRejections?.length??0));assert.ok(transition);const [a,b]=transition;assert.throws(()=>rowPatch(b,{...b,finalRejections:[]}),/HistoryChanged/);assert.deepEqual(b.finalRejections[0].pending,a.pending);
 }finally{await w.context.close();}});
test('C253 a timeout/unknown final is never reselected or repeated',async()=>{const w=await world();try{await w.run();await w.page.evaluate(()=>fakeMode='unknown');const r=await w.run(w.grant());assert.equal(r.finalIntent.sent,true);assert.equal(r.finalRejections,undefined);await w.run();assert.equal(await w.page.evaluate(()=>fakeFinals),1);assert.equal(w.state.actions.filter(x=>x==='chooseSlot').length,1);}finally{await w.context.close();}});
for(const [label,edit]of [
 ['legacy final without command witness',()=>delete globalThis.__applebuyControlledCheckout.finalAction],
 ['human intervention',()=>globalThis.__applebuyControlledCheckout.intervened=true],
 ['unrelated error',()=>document.querySelector('.rt-messages-text').textContent='FAKE network error'],
 ['duplicate alert',()=>{const a=document.querySelector('[role="alert"]');a.after(a.cloneNode(true));}],
 ['different total',()=>document.querySelector('[data-autom="companionbar-button"]').textContent='显示订单摘要： RMB 10,000'],
 ['replaced main',()=>{const m=document.querySelector('main');m.replaceWith(m.cloneNode(true));}]
])test('C253 '+label+' cannot release a sent final',async()=>{const w=await world();try{await w.run();w.state.afterSubmit=()=>w.page.evaluate(edit);const r=await w.run(w.grant());assert.equal(r.finalIntent.sent,true);assert.equal(r.finalRejections,undefined);assert.equal(await w.page.evaluate(()=>fakeFinals),1);assert.equal(w.state.actions.filter(x=>x==='chooseSlot').length,1);}finally{await w.context.close();}});
