// Codex quota completion tests. Actual job/ChromePort; every API, cart, authority, clock and document is FAKE.
import test from 'node:test';
import assert from 'node:assert/strict';
import {PurchaseJob,NO_EXTRAS} from '../web/checkout-connector/job.js';
import {ChromePort} from '../web/checkout-connector/chrome-port.js';
const plan={schema:'applebuy-intent/v1',product:{model:'iPhone Duo',capacity:'256GB',color:'星光白色'},quantity:1,maxTotalCny:15999,city:'大连',fulfillment:'pickup',stores:['Apple 大连恒隆广场'],dateRule:'initial-first-three-terminal',paymentMethod:'支付宝',extras:{...NO_EXTRAS}};
async function jobCase(kind){let row=null,seq=0,phase='VARIANT',reads=0;const actions=[];let job;
 const good={schema:'applebuy-merchant-read/v1',phase:'EMPTY_BAG',verifiedStep:true,path:'/shop/bag',documentId:'FAKE-side',seq:20};
 const port={observe:async()=>({schema:'applebuy-merchant-read/v1',phase,verifiedStep:phase!=='AUTH',path:phase==='BAG'?'/shop/bag':'/shop/buy-iphone/iphone-duo',documentId:'FAKE-original',seq:++seq,variantVerified:true,quotedCny:15999,nextChoice:null,continueAvailable:true,extras:false,purchase:{...plan.product,quantity:1,totalCny:15999,itemVerified:true}}),readBag:async()=>{reads++;let b={...good,seq:++seq,documentId:'FAKE-side'};
   if(kind==='throw')throw Error('FAKE read transport');if(kind==='unknown')b={...b,phase:'UNKNOWN',verifiedStep:false};if(kind==='stale')b.seq=0;if(kind==='same-document')b.documentId='FAKE-original';if(kind==='pause')job.pause();if(kind==='wrong-item')b={...b,phase:'BAG',extras:false,purchase:{model:'iPhone 18 Pro',capacity:'256GB',color:'黑色',quantity:1,totalCny:9999,itemVerified:true}};if(kind==='matching')b={...b,phase:'BAG',extras:false,purchase:{...plan.product,quantity:1,totalCny:15999,itemVerified:true}};return b;},act:async c=>{actions.push(c.action);if(c.action==='openBag'||c.action==='addBag')phase='BAG';if(c.action==='checkout')phase='AUTH';return {delivered:true};},wait:async()=>{}};
 job=new PurchaseJob({store:{get:async()=>structuredClone(row),put:async(k,v)=>{row=structuredClone(v);}},port,now:()=>1000,id:()=>'FAKE-'+(++seq),maxSteps:20});const result=await job.run(plan,{tabId:7,planDigest:'FAKE-digest'});return {result,actions,reads};}
for(const kind of ['throw','unknown','stale','same-document','pause','wrong-item'])test('C035-R1 fresh initial task: '+kind+' boundary read sends zero Add',async()=>{const r=await jobCase(kind);assert.equal(r.reads,1);assert.equal(r.actions.includes('addBag'),false);assert.equal(r.actions.includes('checkout'),false);if(kind==='pause')assert.equal(r.result.state,'PAUSED');});
test('C035-R1 initial task with current matching one item automatically opens bag and checks out without Add',async()=>{const r=await jobCase('matching');assert.deepEqual(r.actions,['openBag','checkout']);assert.equal(r.result.reason,'auth');assert.equal(r.reads,1);});
test('C035-R1 readBag lost known-tab close is UNKNOWN, no empty clearance',async()=>{let removed=0;const empty={schema:'applebuy-merchant-read/v1',phase:'EMPTY_BAG',verifiedStep:true,purchase:null,extras:null};const api={permissions:{contains:async()=>true},tabs:{create:async()=>({id:8}),get:async()=>({url:'https://www.apple.com.cn/shop/bag',status:'complete'}),remove:async()=>{removed++;throw Error('FAKE close lost');}},scripting:{executeScript:async()=>[{frameId:0,documentId:'FAKE-side',result:empty}]}};const p=new ChromePort(api,7,{authorized:true});p.wait=async()=>{};const r=await p.readBag(plan);assert.equal(removed,1);assert.equal(r.phase,'UNKNOWN');assert.equal(r.verifiedStep,false);assert.equal(r.reason,'BagTabCloseFailed');});
test('C035-R1 observe/public-config/unauthorized reader never creates a tab',async()=>{for(const opts of [{authorized:false},{authorized:true,mode:'observe'},{authorized:true,mode:'public-config'}]){let created=0;const p=new ChromePort({tabs:{create:async()=>{created++;}},permissions:{contains:async()=>true}},7,opts);await assert.rejects(p.readBag(plan),/BagReadNotAuthorized/);assert.equal(created,0);}});
