// The real decoder/writer/controller against a contained native DOM; all account, browser and merchant effects are FAKE.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {createRequire} from 'node:module';import {homedir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';
import {merchantDocument} from '../web/checkout-connector/page-program.js';import {ChromePort} from '../web/checkout-connector/chrome-port.js';
import {PurchaseJob,TASK_KEY,CONTACT_SLOT_BASIS,createPurchaseRecord} from '../web/checkout-connector/job.js';import {PRO_PLAN,proDigest} from '../src/desktop/browser-session.mjs';
const {chromium}=createRequire(import.meta.url)(join(homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const url='https://secure7.www.apple.com.cn/shop/checkout',id='checkout.billing.billingoptions.alipay';let server,browser,origin;
before(async()=>{server=http.createServer((q,r)=>r.end('FAKE native payment fixture'));await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-background-networking']});});
after(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));});
function markup({total=9999,alt='支付宝',duplicate=false,hidden=false,disabled=false,badRelation=false,buttonDisabled=false,otherSelected=false}={}){
 const keys=['alipay','wechat','installments0001243254','installments0001864343','installments0001321713','installments0000882476','installments0000833448','credit'];
 const radios=keys.map(key=>{const keyId='checkout.billing.billingoptions.'+key;return `<input type="radio" name="FAKE-payment" id="${keyId}" aria-labelledby="${keyId}_label" ${key==='alipay'?(hidden?'hidden':'')+(disabled?' disabled':''):otherSelected&&key==='wechat'?' checked':''}><label id="${keyId}_label" for="${badRelation&&key==='alipay'?'FAKE-foreign':keyId}"><img alt="${key==='alipay'?alt:key}"></label>`;}).join('');
 return `<html data-fake="c194"><body><div role="main" id="checkout-container"><h1>你希望如何付款？</h1><button data-autom="companionbar-button">显示订单摘要： RMB ${total.toLocaleString('en-US')}</button><h2>付款选项</h2>${radios}${duplicate?`<input type="radio" id="${id}" aria-label="支付宝">`:''}<button data-autom="continue-button-review" ${buttonDisabled?'disabled':''}>检查订单</button></div></body></html>`;
}
async function world(options={}){
 const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort('blockedbyclient'));await context.routeWebSocket('**/*',s=>s.close());
 const page=await context.newPage();await page.goto(origin);await page.setContent(markup(options));
 const read=(cmd=null,source=merchantDocument.toString())=>page.evaluate(async({source,plan,cmd,url})=>{if(location.hostname!=='127.0.0.1'||document.documentElement.dataset.fake!=='c194')throw Error('OwnedFixtureOnly');return new Function('location','return ('+source+')')({href:url})(plan,cmd);},{source,plan:PRO_PLAN,cmd,url});
 return {context,page,read};
}
test('C194 previous accepted decoder reproduces UNKNOWN for the observed image-labelled payment page',async()=>{
 const w=await world();try{const old=execFileSync('git',['show','6e5c2e6:web/checkout-connector/page-program.js'],{encoding:'utf8'}).replace('export async function merchantDocument','async function merchantDocument');const fn=old.slice(old.indexOf('async function merchantDocument'));
 assert.equal((await w.read(null,fn)).phase,'UNKNOWN');}finally{await w.context.close();}
});
test('C194 native payment is a verified STEP while purchase and extras remain unverified',async()=>{
 const w=await world();try{const o=await w.read();assert.equal(o.phase,'PAYMENT');assert.equal(o.paymentStep?.verified,true);assert.equal(o.purchase.verified,false);assert.equal(o.purchase.itemVerified,false);assert.equal(o.purchase.quantity,null);assert.equal(o.purchase.store,null);assert.equal(o.extras,null);assert.equal(o.paymentMethod,null);}finally{await w.context.close();}
});
for(const [label,options]of [['wrong logo',{alt:'微信支付'}],['duplicate control',{duplicate:true}],['hidden input',{hidden:true}],['disabled input',{disabled:true}],['foreign label',{badRelation:true}],['disabled review',{buttonDisabled:true}],['other selected provider',{otherSelected:true}]])test('C194 '+label+' supplies no payment-only step authority',async()=>{const w=await world(options);try{assert.equal((await w.read()).paymentStep,null);}finally{await w.context.close();}});
for(const [label,change]of [['conflicting explicit accessible label',()=>document.querySelector('input').setAttribute('aria-label','微信支付')],['foreign continuation contract',()=>document.querySelector('[data-autom="continue-button-review"]').setAttribute('data-autom','FAKE-other')],['conflicting main heading',()=>document.querySelector('h1').textContent='FAKE delivery payment']])test('C194 '+label+' remains unverified',async()=>{const w=await world();try{await w.page.evaluate(change);assert.equal((await w.read()).paymentStep,null);}finally{await w.context.close();}});
for(const [label,html]of [['product mention','<p>iPhone 18 Pro 256GB 黑色</p>'],['quantity','<p>数量 2</p>'],['store field','<p>取货门店: Apple 大连恒隆广场</p>'],['delivery text','<p>配送地址: FAKE</p>'],['visible dialog','<div role="dialog" aria-modal="true">FAKE</div>'],['labelled total','<p>总计 RMB 9,999</p>'],['order label','<p>订单号 FAKE123456</p>'],['checkbox','<input type="checkbox" aria-label="FAKE">'],['select','<select><option>FAKE</option></select>'],['extra radio','<input type="radio" id="FAKE-extra">']])test('C194 '+label+' cannot lend payment-only identity or authority',async()=>{const w=await world();try{await w.page.evaluate(html=>document.querySelector('[role="main"]').insertAdjacentHTML('beforeend',html),html);assert.equal((await w.read()).paymentStep,null);}finally{await w.context.close();}});
test('C194 unfamiliar native provider ID is not silently accepted',async()=>{const w=await world();try{await w.page.evaluate(()=>document.querySelectorAll('input')[1].id='FAKE-other');assert.equal((await w.read()).paymentStep,null);}finally{await w.context.close();}});
async function run({total=9999,readonly=false,missingBasis=false,missingSlot=false,wrongDate=false,finalIntent=false,rejected=false,wrongFloor=false,noBagStart=false,expired=false,selectDoesNotSelect=false,rerun=false}={}){
 const w=await world({total}),actions=[];const now=Date.now();let row={...createPurchaseRecord(PRO_PLAN,{taskId:'FAKE-c194',planDigest:proDigest,tabId:7,now,id:()=>crypto.randomUUID()}),state:'NEEDS_VERIFICATION',lastPhase:'DETAILS',bagAddStarted:true,resourceWritten:true,bagTotalCny:missingBasis?null:9999,initialDates:['october8'],dateCursor:0,floors:{october8:'21:15'},acceptedSlot:missingSlot?null:{date:wrongDate?'october9':'october8',start:'21:15',end:'21:30',verified:true,basis:CONTACT_SLOT_BASIS},pending:{id:'FAKE-details',action:'fillDetails',beforePhase:'DETAILS',contactOnly:true,documentId:'FAKE-before',deadline:now-1},...(readonly?{reconcileOnly:true}:{})};
 const api={tabs:{get:async()=>({url,status:'complete'})},permissions:{contains:async()=>true},scripting:{executeScript:async q=>{const c=q.args[1];if(c)actions.push(c.action);const result=await w.read(c??null);return [{frameId:0,documentId:'FAKE-payment-document',result}];}}};
 if(finalIntent)row.finalIntent={id:'FAKE-final',sent:false};if(rejected)row.rejected=[{date:'october8',start:'21:15',end:'21:30',generation:1}];if(wrongFloor)row.floors.october8='21:30';if(noBagStart)row.bagAddStarted=false;if(expired)row.expiresAt=now-1;
 if(selectDoesNotSelect)await w.page.evaluate(()=>document.querySelector('input').addEventListener('click',e=>e.preventDefault()));
 await w.page.evaluate(()=>{document.querySelector('[data-autom="continue-button-review"]').onclick=()=>{document.querySelector('[role="main"]').innerHTML='<h1>FAKE unverified review</h1><button>立即下单</button>';};});
 const store={get:async()=>structuredClone(row),put:async(k,v)=>{assert.equal(k,TASK_KEY);row=structuredClone(v);}},port=new ChromePort(api,7,{authorized:!readonly,mode:readonly?'observe':'purchase',acceptedSlot:row.acceptedSlot,pending:row.pending});
 try{let result=await new PurchaseJob({store,port,maxWaitMs:0}).run(PRO_PLAN,{tabId:7,planDigest:proDigest});if(rerun)result=await new PurchaseJob({store,port,maxWaitMs:0}).run(PRO_PLAN,{tabId:7,planDigest:proDigest});return {result,row,actions};}finally{await w.context.close();}
}
test('C194 current originating contact continuation reaches review through one Alipay selection and one review click, without repeating contact/slot/checkout or submitting',async()=>{
 const {result,actions}=await run();assert.deepEqual(actions,['selectPayment','continuePayment']);assert.equal(result.lastPhase,'REVIEW');assert.equal(result.finalIntent,null);assert.equal(result.state,'NEEDS_VERIFICATION');assert.equal(result.pending.action,'continuePayment');
});
for(const [label,options]of [['changed total',{total:10000}],['changed total still under cap',{total:9998}],['readonly task',{readonly:true}],['missing money basis',{missingBasis:true}],['missing accepted slot',{missingSlot:true}],['foreign accepted date',{wrongDate:true}]])test('C194 '+label+' cannot acknowledge contact and send a payment action',async()=>{const {actions,result}=await run(options);assert.deepEqual(actions,[]);assert.equal(result.pending.action,'fillDetails');assert.equal(result.finalIntent,null);});
for(const [label,options]of [['existing final intent',{finalIntent:true}],['rejected slot',{rejected:true}],['terminal floor mismatch',{wrongFloor:true}],['no earlier bag start',{noBagStart:true}],['expired original task',{expired:true}]])test('C194 '+label+' stops without any payment or final action',async()=>{const {actions}=await run(options);assert.deepEqual(actions,[]);});
test('C194 an unconfirmed selection is not retried on rerun',async()=>{const {actions,result}=await run({selectDoesNotSelect:true,rerun:true});assert.deepEqual(actions,['selectPayment']);assert.equal(result.pending.action,'selectPayment');assert.equal(result.finalIntent,null);});
test('C194 an unconfirmed review transition is not retried on rerun',async()=>{const {actions,result}=await run({rerun:true});assert.deepEqual(actions,['selectPayment','continuePayment']);assert.equal(result.pending.action,'continuePayment');assert.equal(result.finalIntent,null);});
