// Contained real DOM/production parser/port/job. Every merchant, identity and resulting order is FAKE.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {createRequire} from 'node:module';import {homedir} from 'node:os';import {join} from 'node:path';
import {merchantDocument} from '../web/checkout-connector/page-program.js';import {ChromePort} from '../web/checkout-connector/chrome-port.js';
import {PurchaseJob,createPurchaseRecord,TASK_KEY,CONTACT_SLOT_BASIS} from '../web/checkout-connector/job.js';
import {PRO_PLAN,proDigest} from '../src/desktop/browser-session.mjs';import {currentReviewProgress} from '../web/checkout-connector/review-progress.js';
import {CheckoutRpcPeer} from '../web/checkout-connector/checkout-rpc-peer.js';
import {NativeCheckoutApi} from '../src/desktop/native-checkout-api.mjs';
import {DesktopCheckoutRuntime} from '../src/desktop/checkout-runtime.mjs';
const {chromium}=createRequire(import.meta.url)(join(homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const address='https://secure10.www.apple.com.cn/shop/checkout',terms='https://www.apple.com.cn/shop/browse/open/salespolicies';let server,browser,origin;
before(async()=>{server=http.createServer((q,r)=>r.end('FAKE C209'));await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-background-networking']});});
after(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));});
const slots='<h1>FAKE pickup</h1><h2>iPhone 18 Pro 256GB 黑色</h2><p>数量 1</p><p>总计 RMB 9,999</p><button role="radio" aria-checked="true">我要取货</button><input type="radio" checked aria-label="Apple 大连恒隆广场"><select aria-label="取货日期"><option>October 8</option></select><select aria-label="取货时间"><option>可选时段</option><option>21:00 – 21:15</option><option>21:15 – 21:30</option></select><button id="next">继续填写取货详情</button>';
const contact='<h1>FAKE contact</h1><button data-autom="companionbar-button">显示订单摘要： RMB 9,999</button>'+[['姓氏','text'],['名字','text'],['电子邮件地址','email'],['联系人手机号码','tel'],['政府颁发的身份证件号码的后四位','text']].map(([n,t],i)=>`<input type="${t}" aria-label="${n}" required value="${i===2?'FAKE@example.invalid':i===3?'12345678901':i===4?'1234':'FAKE'}" ${i===4?'maxlength="4"':''}>`).join('')+'<button id="details">继续选择付款方式</button>';
const providerKeys=['alipay','wechat','credit','installments0001243254','installments0001864343','installments0001321713','installments0000882476','installments0000833448'];
const payment='<h1>你希望如何付款？</h1><button data-autom="companionbar-button">显示订单摘要： RMB 9,999</button>'+providerKeys.map(k=>{const id='checkout.billing.billingoptions.'+k;return `<input type="radio" name="FAKE-provider" id="${id}" aria-labelledby="${id}_label"><label id="${id}_label" for="${id}"><img alt="${k==='alipay'?'支付宝':k}"></label>`;}).join('')+'<button id="payment" data-autom="continue-button-review">检查订单</button>';
const review='<h1 class="rs-review-header">准备下单了吗？<span>请确保以下信息均准确无误。</span></h1><div class="rs-review-fulfillment"><h2 class="rs-review-shipquote">取货日期待付款完成后确定。</h2><button data-autom="changeShippingMethod">更改零售店</button><h2>iPhone 18 Pro 256GB 黑色</h2><p>数量 1</p><p>总计 RMB 9,999</p></div><div class="rs-review-billing"><h2 class="rs-review-title">付款方式</h2><div class="rs-review-billing-details"><div class="rs-review-billing-cards"><h3 class="rs-review-payment-header"><img class="rs-review-payment-image" alt="支付宝"></h3></div></div></div><a href="'+terms+'">条款和条件</a><button id="final">立即下单</button>';
async function world(){
 const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort('blockedbyclient'));await context.routeWebSocket('**/*',s=>s.close());const page=await context.newPage();page.setDefaultTimeout(5000);await page.goto(origin,{waitUntil:'domcontentloaded'});await page.setContent('<html data-fake="c209"><body><div role="main" id="checkout-container">'+slots+'</div></body></html>',{waitUntil:'domcontentloaded'});
 await page.evaluate(({contact,payment,review})=>{const main=document.querySelector('[role="main"]');document.getElementById('next').onclick=()=>{main.innerHTML=contact;document.getElementById('details').onclick=()=>{main.innerHTML=payment;document.getElementById('payment').onclick=()=>{main.innerHTML=review;document.getElementById('final').onclick=()=>{document.documentElement.dataset.fakeFinals=String(Number(document.documentElement.dataset.fakeFinals||0)+1);};};};};},{contact,payment,review});
 const read=(cmd=null)=>page.evaluate(async({source,plan,cmd,address})=>{if(location.hostname!=='127.0.0.1'||document.documentElement.dataset.fake!=='c209')throw Error('OwnedFixtureOnly');return new Function('location','return ('+source+')')({href:address})(plan,cmd);},{source:merchantDocument.toString(),plan:PRO_PLAN,cmd,address});
 let counter=0;const api={sessionId:'FAKE-current-controlled-context',controlledReview:true,tabs:{get:async()=>({url:address,status:'complete'})},permissions:{contains:async()=>true},scripting:{executeScript:async q=>[{frameId:0,documentId:'FAKE-controlled-document',result:await read(q.args[1]??null)}]}};
 const row={...createPurchaseRecord(PRO_PLAN,{taskId:'FAKE-c209-task',planDigest:proDigest,tabId:7,now:Date.now(),id:()=>crypto.randomUUID()}),bagAddStarted:true,resourceWritten:true,bagTotalCny:9999,initialDates:['October 8'],dateCursor:0,floors:{'October 8':'21:15'}};
 const action=async(name,extra={})=>{const expected=await read();return read({action:name,id:'FAKE-action-'+(++counter),taskId:row.taskId,planDigest:proDigest,authorized:true,structured:true,expected:JSON.stringify(expected),...extra});};
 return {context,page,api,row,read,action};
}
async function reach(w){const s=await w.read();assert.equal(s.purchase.verified,true);const t=s.times.at(-1);assert.equal((await w.action('chooseSlot',{date:s.selectedDate,start:t.start,end:t.end,ref:t.ref})).delivered,true);assert.equal((await w.read()).contactStep?.verified,true);assert.equal((await w.action('fillDetails',{contactOnly:true})).delivered,true);assert.equal((await w.read()).paymentStep?.verified,true);assert.equal((await w.action('selectPayment',{paymentOnly:true})).delivered,true);assert.equal((await w.action('continuePayment',{paymentOnly:true})).delivered,true);}
test('C209 actual originating native slot/contact/payment gives separately labelled REVIEW progress, no merchant store/slot or hold invented',async()=>{const w=await world();try{await reach(w);const o=await w.read();assert.equal(o.phase,'REVIEW');assert.equal(o.reviewProgress?.controlled,true,JSON.stringify({purchase:o.purchase,method:o.paymentMethod,extras:o.extras,terms:o.primaryTermsUrl,trace:await w.page.evaluate(()=>{const t=globalThis.__applebuyControlledCheckout;return t?{stage:t.stage,intervened:t.intervened,total:t.totalCny,sameMain:t.main===document.querySelector('[role="main"]')}:null;})}));assert.equal(o.reviewProgress.store,PRO_PLAN.stores[0]);assert.equal(o.purchase.store,null);assert.equal(o.purchase.verified,false);assert.equal(o.slotSummary,null);}finally{await w.context.close();}});
test('C209 a bare review without originating native trace cannot become source-bound proof',async()=>{const w=await world();try{await w.page.evaluate(review=>document.querySelector('[role="main"]').innerHTML=review,review);assert.equal((await w.read()).reviewProgress,null);}finally{await w.context.close();}});
test('C209 trusted human intervention invalidates the native originating trace',async()=>{const w=await world();try{await reach(w);await w.page.getByRole('button',{name:'更改零售店',exact:true}).click();assert.equal((await w.read()).reviewProgress,null);}finally{await w.context.close();}});
test('C209 current source-bound pending payment can settle but cannot final without new precise consent',async()=>{const w=await world();try{await reach(w);let row={...w.row,state:'NEEDS_VERIFICATION',acceptedSlot:{date:'October 8',start:'21:15',end:'21:30',verified:true,basis:CONTACT_SLOT_BASIS},pending:{id:'FAKE-pending',action:'continuePayment',beforePhase:'PAYMENT',paymentOnly:true,documentId:'FAKE-controlled-document',deadline:Date.now()-1}};const store={get:async()=>structuredClone(row),put:async(k,v)=>{assert.equal(k,TASK_KEY);row=structuredClone(v);}},port=new ChromePort(w.api,7,{authorized:true,pending:row.pending,acceptedSlot:row.acceptedSlot});await new PurchaseJob({store,port,maxWaitMs:0}).run(PRO_PLAN,{tabId:7,planDigest:proDigest});assert.equal(row.pending,null);assert.ok(row.reviewProgress);assert.equal(row.finalIntent,null);assert.equal(await w.page.evaluate(()=>document.documentElement.dataset.fakeFinals||'0'),'0');}finally{await w.context.close();}});
test('C212 full native parser-peer-API-runtime-job progression reaches disclosed consent and sends exactly one final; unknown receipt is never called an order or resent',async()=>{
 const w=await world(),contextId='FAKE-full-native-current-context';let row={...w.row,desktopContext:contextId};const actions=[];
 const chrome={tabs:{create:async()=>({id:7,status:'complete'}),get:w.api.tabs.get,remove:async()=>{}},permissions:w.api.permissions,scripting:{executeScript:async q=>{if(q.args[1])actions.push(q.args[1].action);return w.api.scripting.executeScript(q);}}};
 const peer=new CheckoutRpcPeer({api:chrome,contextId,purchaseAllowed:true}),api=new NativeCheckoutApi({contextId,exchange:q=>peer.receive(q)}),store={get:async()=>structuredClone(row),put:async(k,v)=>{assert.equal(k,TASK_KEY);row=structuredClone(v);},acquireOwner:async()=>({owned:true,release:async()=>{}})};
 const runtime=new DesktopCheckoutRuntime({store,launch:async()=>({api,close:()=>api.close()})});
 try{await runtime.open();const ready=await runtime.advance({checkoutApproved:true,newContextConfirmed:true});assert.equal(ready.phase,'REVIEW');assert.equal(row.pending,null);assert.ok(runtime.finalDescriptor?.reviewProgressId);assert.equal(runtime.finalDescriptor.sourceChoice.store,PRO_PLAN.stores[0]);assert.equal(runtime.finalDescriptor.pickupNotice,'取货日期待付款完成后确定。');assert.deepEqual(actions,['chooseSlot','fillDetails','selectPayment','continuePayment']);
  await assert.rejects(runtime.submit({termsAccepted:true,existingOrdersChecked:true,noExtras:true}),/FinalConsentNotCurrent/);assert.notEqual(row.state,'CONFIRMED_UNPAID');assert.equal(row.finalIntent.sent,true);assert.equal(row.pending.action,'submitOrder');assert.equal(actions.filter(a=>a==='submitOrder').length,1);assert.equal(await w.page.evaluate(()=>document.documentElement.dataset.fakeFinals),'1');await assert.rejects(runtime.submit({termsAccepted:true,existingOrdersChecked:true,noExtras:true}),/FinalConsent/);assert.equal(actions.filter(a=>a==='submitOrder').length,1);
 }finally{await runtime.close();await w.context.close();}
});
for(const [name,change]of [['foreign task',r=>r.taskId='FAKE-foreign'],['foreign source store',r=>r.store='FAKE store'],['intervention',r=>r.intervened=true],['wrong date',r=>r.date='October 9'],['wrong floor time',r=>r.start='21:00']])test('C212 '+name+' cannot validate a current carried selection',async()=>{const w=await world();try{await reach(w);const port=new ChromePort(w.api,7,{authorized:true}),o=await port.observe(PRO_PLAN);change(o.reviewProgress);const row={...w.row,acceptedSlot:{date:'October 8',start:'21:15',end:'21:30',verified:true,basis:CONTACT_SLOT_BASIS},pending:{action:'continuePayment',beforePhase:'PAYMENT',paymentOnly:true,documentId:o.documentId}};assert.equal(currentReviewProgress(PRO_PLAN,row,o,{contextOwned:true}),null);}finally{await w.context.close();}});
test('C212 a replaced main element cannot inherit an earlier trace',async()=>{const w=await world();try{await reach(w);await w.page.evaluate(()=>{const main=document.querySelector('[role="main"]');main.replaceWith(main.cloneNode(true));});assert.equal((await w.read()).reviewProgress,null);}finally{await w.context.close();}});
test('C212 returning to slots after contact/payment cannot mint a replacement accepted trace or click another slot continuation',async()=>{const w=await world();try{await reach(w);await w.page.evaluate(slots=>document.querySelector('[role="main"]').innerHTML=slots,slots);const before=await w.read(),last=before.times.at(-1),r=await w.action('chooseSlot',{date:before.selectedDate,start:last.start,end:last.end,ref:last.ref});assert.equal(r.delivered,false);assert.equal(r.touched,false);assert.equal(r.reason,'ControlledSlotAlreadyProgressed');assert.equal((await w.read()).reviewProgress,null);}finally{await w.context.close();}});
