// Isolated real renderer with fictional fields; no authenticated network/profile/merchant calls.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {createRequire} from 'node:module';import {homedir} from 'node:os';import {join} from 'node:path';
import {AppleLogin,loginForm,loginFrameIdentity,loginParentDocument,APPLE_AUTH_ORIGIN} from '../web/checkout-connector/apple-login.js';
import {CheckoutRpcPeer} from '../web/checkout-connector/checkout-rpc-peer.js';
import {NativeCheckoutApi} from '../src/desktop/native-checkout-api.mjs';
import {guardOwnedApi} from '../src/desktop/owner-lease.mjs';
const {chromium}=createRequire(import.meta.url)(join(homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const account='fake@example.invalid',password='FAKE-secret-257';const auth='https://idmsa.apple.com.cn/appleauth/auth/authorize/signin';
let server,browser,origin;
before(async()=>{server=http.createServer((q,r)=>r.end('FAKE'));await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-background-networking']});});
after(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));});
async function world(){
 const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort('blockedbyclient'));await context.routeWebSocket('**/*',s=>s.close());const page=await context.newPage();await page.goto(origin);let location=auth;
 const render=async(html=`<h1>使用你的 Apple 账户</h1><input type="email" aria-label="电子邮件或电话号码" value="${account}"><input type="password" aria-label="密码"><button aria-label="登录">登录</button>`)=>{await page.setContent(html);await page.evaluate(()=>{globalThis.__applebuyLoginAttempts=new Set();globalThis.clicked=0;document.querySelector('button')?.addEventListener('click',()=>globalThis.clicked++);});};await render();
 const run=(fn,args=[])=>page.evaluate(({fn,args,url})=>new Function('location','return ('+fn+')')({href:url,origin:new URL(url).origin,pathname:new URL(url).pathname})(...args),{fn:fn.toString(),args,url:location});
 return {page,context,render,run,setUrl:v=>location=v,clicks:()=>page.evaluate(()=>globalThis.clicked)};
}
test('C257 normal password input events and single click, no secret in result and no duplicate',async()=>{const w=await world();try{let r=await w.run(loginForm,[account]);assert.deepEqual(r,{state:'password'});const c={stage:'password',secret:password,attempt:'7:password'};r=await w.run(loginForm,[account,c]);assert.deepEqual(r,{state:'submitted'});assert.equal(await w.page.locator('input[type=password]').inputValue(),password);assert.deepEqual(await w.run(loginForm,[account,c]),{state:'already-attempted'});assert.equal(await w.clicks(),1);}finally{await w.context.close();}});
test('C257 account then password stages; disabled button enabled by input event only',async()=>{const w=await world();try{await w.render('<input aria-label="电子邮件或电话号码"><button disabled aria-label="继续">继续</button>');await w.page.evaluate(()=>document.querySelector('input').addEventListener('input',()=>document.querySelector('button').disabled=false));assert.deepEqual(await w.run(loginForm,[account,{stage:'account',attempt:'7:account'}]),{state:'submitted'});assert.equal(await w.clicks(),1);}finally{await w.context.close();}});
for(const [name,html]of [
 ['OTP','<input autocomplete="one-time-code">'],['alert','<div role="alert">密码错误</div>'],['terms','<h2>条款</h2>'],['trust','<h2>信任此浏览器</h2>'],['additional field','<input aria-label="安全问题">']
])test('C257 '+name+' requires person without input or click',async()=>{const w=await world();try{await w.page.locator('body').evaluate((b,html)=>b.insertAdjacentHTML('beforeend',html),html);assert.deepEqual(await w.run(loginForm,[account,{stage:'password',secret:password,attempt:'x'}]),{state:'changed'});assert.equal(await w.clicks(),0);assert.equal(await w.page.locator('input[type=password]').inputValue(),'');}finally{await w.context.close();}});
test('C257 mismatched account and foreign origin never get a password',async()=>{const w=await world();try{await w.page.locator('input[type=email]').fill('different@example.invalid');assert.deepEqual(await w.run(loginForm,[account]),{state:'account-mismatch'});w.setUrl('https://evil.invalid/appleauth/auth/authorize/signin');assert.deepEqual(await w.run(loginForm,[account,{stage:'password',secret:password,attempt:'x'}]),{state:'unsupported'});assert.equal(await w.clicks(),0);}finally{await w.context.close();}});
test('C257 DOM replacement after input prevents click',async()=>{const w=await world();try{await w.page.evaluate(()=>document.querySelector('input[type=password]').addEventListener('input',()=>document.querySelector('button').remove()));assert.deepEqual(await w.run(loginForm,[account,{stage:'password',secret:password,attempt:'x'}]),{state:'changed'});assert.equal(await w.clicks(),0);}finally{await w.context.close();}});
test('C257 existing visible browser-filled password can submit without returning or changing it',async()=>{const w=await world();try{const c={stage:'password',secret:'',attempt:'auto'};assert.deepEqual(await w.run(loginForm,[account,c]),{state:'password-needed'});assert.equal(await w.clicks(),0);await w.page.locator('input[type=password]').fill('FAKE-browser-filled');assert.deepEqual(await w.run(loginForm,[account,c]),{state:'submitted'});assert.equal(await w.page.locator('input[type=password]').inputValue(),'FAKE-browser-filled');assert.equal(await w.clicks(),1);}finally{await w.context.close();}});
function fakeTransport(){const calls=[];let grant=true,stage='password',live=true,ambiguous=false,fail=false;const api={permissions:{contains:async p=>{assert.deepEqual(p.origins,[APPLE_AUTH_ORIGIN]);return grant;}},scripting:{executeScript:async q=>{calls.push(q);if(q.func===loginParentDocument)return[{frameId:0,documentId:'top',result:true}];if(q.func===loginFrameIdentity){assert.deepEqual(q.args,[]);return [{frameId:0,documentId:'top',result:false},{frameId:2,documentId:'auth',result:true},...(ambiguous?[{frameId:3,documentId:'other',result:true}]:[])];}assert.equal(q.func,loginForm);assert.deepEqual(q.target,{tabId:7,documentIds:['auth']});if(fail)throw Error('FAKE '+password);return [{frameId:2,documentId:'auth',result:{state:q.args[1]?'submitted':stage}}];}}};return{api,calls,setGrant:v=>grant=v,setStage:v=>stage=v,setAmbiguous:v=>ambiguous=v,setFail:v=>fail=v,lose:()=>live=false,live:()=>{if(!live)throw Error('OwnerLost');}};}
test('C257 secret only to identified unique document, once per tab across frame replacement',async()=>{const f=fakeTransport(),a=new AppleLogin();a.configure({account,password});assert.deepEqual(await a.attempt(f.api,7),{state:'submitted'});assert.deepEqual(await a.attempt(f.api,7),{state:'waiting'});assert.equal(f.calls.filter(q=>q.args[1]?.secret).length,1);assert.ok(f.calls.filter(q=>q.target.allFrames).every(q=>q.args.length===0));});
test('C257 permission and ambiguous frame never dispatch credential input',async()=>{for(const ambiguous of [false,true]){const f=fakeTransport(),a=new AppleLogin();a.configure({account,password});f.setGrant(ambiguous);f.setAmbiguous(ambiguous);await a.attempt(f.api,7);assert.equal(f.calls.filter(q=>q.func===loginForm).length,0);}});
test('C257 failed result never retries or leaks raw error; pause clear stops next read',async()=>{const f=fakeTransport(),a=new AppleLogin();a.configure({account,password});f.setFail(true);assert.deepEqual(await a.attempt(f.api,7),{state:'unconfirmed'});const n=f.calls.length;a.configure({account,password});await a.attempt(f.api,7);assert.equal(f.calls.length,n);a.clear();assert.equal(a.credentials,null);});
test('C257 owner loss or expired five minute window dispatches no secret',async()=>{for(const expired of [false,true]){let now=0;const f=fakeTransport(),a=new AppleLogin({now:()=>now});a.configure({account,password});if(expired)now=300001;else f.lose();await a.attempt(f.api,7,f.live);assert.equal(f.calls.length,0);assert.equal(a.credentials,null);}});
test('C257 configureLogin native reply does not contain credentials; lost lease blocks configuration',async()=>{const f=fakeTransport(),peer=new CheckoutRpcPeer({api:{...f.api,tabs:{}},contextId:'FAKE-C257-native-context'}),api=new NativeCheckoutApi({contextId:peer.contextId,exchange:q=>peer.receive(q)});assert.deepEqual(await api.configureLogin({account,password}),{state:'configured'});assert.throws(()=>peer.login.configure({...{account,password},cookie:'FAKE'}));const lease={owned:false};await assert.rejects(guardOwnedApi(api,lease).configureLogin({account,password}),/OwnerLeaseLost/);peer.dispose();assert.equal(peer.login.credentials,null);});
