// Owned FAKE native form; no personal Chrome, real values, merchant or permissions.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {createRequire} from 'node:module';import {homedir} from 'node:os';import {join} from 'node:path';
import {merchantDocument} from '../web/checkout-connector/page-program.js';import {PRO_PLAN} from '../src/desktop/browser-session.mjs';
const {chromium}=createRequire(import.meta.url)(join(homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
let browser,server,origin;
before(async()=>{server=http.createServer((q,r)=>r.end('<!doctype html><html data-fake="c167"><body></body></html>'));await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-background-networking']});});
after(async()=>{await browser?.close();server?.closeAllConnections?.();if(server)await new Promise(r=>server.close(r));});
async function run({supplied={identitySuffix:'5423'},email='FAKE-invalid',customError=false,extraRequired=false,emailMin=0,emailMax=64,emailPattern=null}={}){
 const c=await browser.newContext({serviceWorkers:'block'});await c.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort('blockedbyclient'));await c.routeWebSocket('**/*',s=>s.close());
 try{const p=await c.newPage();await p.goto(origin);await p.setContent(`<html data-fake="c167"><body><main><h1>FAKE取货资料</h1><button data-autom="companionbar-button">显示订单摘要： RMB 9,999</button><label for="last">姓氏</label><input id="last" required value="FAKE"><label for="first">名字</label><input id="first" required value="TEST"><label for="email">电子邮件地址</label><input id="email" type="email" required maxlength="64" value="${email}"><label for="phone">联系人手机号码</label><input id="phone" type="tel" required value="00000000000"><label for="identity">政府颁发的身份证件号码的后四位</label><input id="identity" maxlength="4" required>${extraRequired?'<input required id="extra">':''}<button id="next">继续选择付款方式</button></main></body></html>`);
  await p.evaluate(custom=>{globalThis.c167={events:[],continued:0};for(const e of document.querySelectorAll('input')){e.addEventListener('input',()=>globalThis.c167.events.push(e.id+':input'));e.addEventListener('change',()=>globalThis.c167.events.push(e.id+':change'));}document.getElementById('next').onclick=()=>globalThis.c167.continued++;if(custom)document.getElementById('email').setCustomValidity('FAKE native rejection');},customError);
  await p.evaluate(({min,max,pattern})=>{const e=document.getElementById('email');e.minLength=min;e.maxLength=max;if(pattern!==null)e.pattern=pattern;},{min:emailMin,max:emailMax,pattern:emailPattern});
  const result=await p.evaluate(async({source,plan,supplied})=>{if(location.hostname!=='127.0.0.1'||document.documentElement.dataset.fake!=='c167')throw Error('OwnedFixtureOnly');const fn=new Function('location','return ('+source+')')({href:'https://secure11.www.apple.com.cn/shop/checkout'}),o=await fn(plan);return await fn(plan,{id:'FAKE-c167-write',taskId:'FAKE-c167-task',action:'fillDetails',contactOnly:true,privatePickupData:supplied,authorized:true,structured:true,expected:JSON.stringify(o)});},{source:merchantDocument.toString(),plan:PRO_PLAN,supplied});
  const state=await p.evaluate(()=>({...globalThis.c167,identity:document.getElementById('identity').value,email:document.getElementById('email').value}));return {result,state};
 }finally{await c.close();}
}
test('C167 invalid prefilled email without a correction stops before the identity write',async()=>{const {result,state}=await run();assert.equal(result.delivered,false);assert.equal(result.touched,false);assert.deepEqual(state.events,[]);assert.equal(state.identity,'');assert.equal(state.continued,0);});
test('C167 invalid supplied correction stops before all private writes',async()=>{const {result,state}=await run({supplied:{email:'FAKE-invalid',identitySuffix:'5423'}});assert.equal(result.touched,false);assert.deepEqual(state.events,[]);assert.equal(state.continued,0);});
test('C167 explicitly supplied valid email and suffix continue once without echo',async()=>{const {result,state}=await run({supplied:{email:'fake-correction@example.invalid',identitySuffix:'5423'}});assert.equal(result.delivered,true);assert.equal(state.continued,1);assert.deepEqual(state.events,['email:input','email:change','identity:input','identity:change']);assert.equal(state.email,'fake-correction@example.invalid');assert.equal(JSON.stringify(result).includes('fake-correction'),false);assert.equal(JSON.stringify(result).includes('5423'),false);});
test('C167 valid prefilled email stays unchanged when only the suffix is supplied',async()=>{const {result,state}=await run({email:'fake-prefill@example.invalid'});assert.equal(result.delivered,true);assert.deepEqual(state.events,['identity:input','identity:change']);assert.equal(state.email,'fake-prefill@example.invalid');assert.equal(state.continued,1);});
test('C167 native custom error cannot be bypassed by detached validation',async()=>{const {result,state}=await run({customError:true,supplied:{email:'fake-correction@example.invalid',identitySuffix:'5423'}});assert.equal(result.touched,false);assert.deepEqual(state.events,[]);assert.equal(state.continued,0);});
test('C167 another unfilled required receiver stops before a provided value is transmitted',async()=>{const {result,state}=await run({email:'fake-valid@example.invalid',extraRequired:true});assert.equal(result.touched,false);assert.deepEqual(state.events,[]);assert.equal(state.continued,0);});
for(const [name,options]of [['minimum length',{emailMin:40}],['maximum length',{emailMax:8}],['native pattern',{emailPattern:'allowed@example\\.invalid'}]])test('C169 '+name+' rejects an explicit correction before any value or Continue',async()=>{const {result,state}=await run({...options,supplied:{email:'fake-correction@example.invalid',identitySuffix:'5423'}});assert.equal(result.reason,'PickupDetailsRequireHuman');assert.equal(result.touched,false);assert.deepEqual(state.events,[]);assert.equal(state.continued,0);});
