// C060 actual control.js handler VM; every Chrome API/storage/merchant/permission is FAKE. No personal browser.
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {webcrypto,createHash} from 'node:crypto';
import {PurchaseJob,TASK_KEY,VALIDATION_KEY,NO_EXTRAS,retirable} from '../web/checkout-connector/job.js';
import {ChromePort,allowedMerchantUrl} from '../web/checkout-connector/chrome-port.js';import {withPurchaseOwner} from '../web/checkout-connector/owner.js';import {taskDiagnostic} from '../web/checkout-connector/task-diagnostic.js';import {probeClosedCheckout} from '../web/checkout-connector/closed-checkout-probe.js';import {restartExpiredPreFinal} from '../web/checkout-connector/pre-final-restart.js';
const plan={schema:'applebuy-intent/v1',product:{model:'iPhone 18 Pro',capacity:'256GB',color:'黑色'},quantity:1,maxTotalCny:9999,city:'大连',fulfillment:'pickup',stores:['Apple 大连恒隆广场'],dateRule:'initial-first-three-terminal',paymentMethod:'支付宝',extras:{...NO_EXTRAS}};
async function control({owned=true,read=null}={}){
 const h={row:{schema:'applebuy-purchase-job/v1',taskId:'FAKE-c060-control-old',plan,planDigest:createHash('sha256').update(JSON.stringify(plan)).digest('hex'),tabId:6,state:'NEEDS_VERIFICATION',lastRead:4,lastPhase:'UNKNOWN',lastDocumentId:'FAKE-original',expiresAt:90000,initialDates:['october5'],dateCursor:0,floors:{october5:'21:15'},rejected:[],refusals:0,pending:{id:'FAKE-choice',action:'chooseSlot',documentId:'FAKE-slots',beforePhase:'SLOTS',deadline:99000,date:'october5',start:'21:15',end:'21:30'},acceptedSlot:null,finalIntent:null,bagAddStarted:true,resourceWritten:true,history:[],retiredHistory:[]},writes:0,commands:[],uri:'https://www.apple.com.cn/shop/bag',privateReads:0};h.before=structuredClone(h.row);
 const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{value:'',checked:false,disabled:false,textContent:'',href:'',replaceChildren(){}});return nodes.get(id);};node('product').value='pro';node('tab').value='7';node('approve').checked=true;node('restartConfirm').checked=true;node('finalReview').checked=true;
 const chrome={storage:{local:{async get(k){return {[k]:structuredClone(h.row)};},async set(v){h.writes++;h.row=structuredClone(v[TASK_KEY]);}},session:{async get(){h.privateReads++;return {};},async set(){throw Error('No private write');}}},tabs:{async query(){return [{id:7,url:h.uri}];},async get(){return {id:7,url:h.uri,status:'complete'};},async update(id,{url}){h.uri=url;return {id,url,status:'complete'};}},permissions:{async contains(){return true;}},scripting:{async executeScript(q){if(q.args.length>1){h.commands.push(q.args[1].action);return [{frameId:0,documentId:q.target.documentIds[0],result:{delivered:true}}];}if(read)await read();const bag=h.uri.endsWith('/bag');return [{frameId:0,documentId:bag?'FAKE-empty':'FAKE-product',result:{schema:'applebuy-merchant-read/v1',phase:bag?'EMPTY_BAG':'PRELAUNCH',path:bag?'/shop/bag':'/shop/buy-iphone/iphone-18-pro',verifiedStep:true,prelaunchConfigurable:false}}];}}};
 const locks={async request(name,opt,fn){assert.equal(name,'applebuy-single-purchase-owner');assert.equal(opt.ifAvailable,true);return fn(owned?{}:null);}};
 const ctx=vm.createContext({document:{getElementById:node},chrome,navigator:{locks},crypto:webcrypto,TextEncoder,URL,structuredClone,Date:class extends Date{static now(){return 100000;}},PurchaseJob,ChromePort,allowedMerchantUrl,withPurchaseOwner,taskDiagnostic,probeClosedCheckout,restartExpiredPreFinal,TASK_KEY,VALIDATION_KEY,NO_EXTRAS,retirable});
 const source=readFileSync(new URL('../web/checkout-connector/control.js',import.meta.url),'utf8').replace(/^import .*;\r?$/gm,'');await vm.runInContext('(async()=>{'+source+'\n})()',ctx);h.writes=0;return {h,node,click:id=>node(id).onclick()};
}
test('C060 actual handler creates one successor and delegates normal flow without stale final consent',async()=>{
 const c=await control();await c.click('restartPreFinal');assert.notEqual(c.h.row.taskId,c.h.before.taskId);assert.deepEqual(c.h.row.retiredHistory.at(-1).abandonedPreFinal.originalSnapshot,c.h.before);assert.equal(c.node('finalReview').checked,false);assert.equal(c.node('final').disabled,true);assert.deepEqual(c.h.commands,['openProduct']);assert.equal(c.h.row.finalIntent,null);assert.equal(c.h.row.state,'NOT_RELEASED');
 const n=c.h.row.taskId;await c.click('restartPreFinal');assert.equal(c.h.row.taskId,n);assert.deepEqual(c.h.commands,['openProduct']);
});
test('C060 actual handler requires current confirmations and owner before any new state',async()=>{
 const a=await control();a.node('restartConfirm').checked=false;await a.click('restartPreFinal');assert.equal(a.h.writes,0);assert.deepEqual(a.h.row,a.h.before);
 const b=await control({owned:false});await b.click('restartPreFinal');assert.equal(b.h.writes,0);assert.deepEqual(b.h.commands,[]);assert.deepEqual(b.h.row,b.h.before);
});
test('C060 pause during the fresh bag read suppresses successor creation and merchant action',async()=>{
 let resolve,signal;const entered=new Promise(r=>signal=r);const c=await control({read:()=>new Promise(r=>{resolve=r;signal();})});const running=c.click('restartPreFinal');await entered;await c.click('pause');resolve();await running;assert.equal(c.h.writes,0);assert.deepEqual(c.h.commands,[]);assert.deepEqual(c.h.row,c.h.before);
});
