// Real isolated renderer; all accounts, references, transport and merchant responses are fictional.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {createRequire} from 'node:module';import {homedir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {orderDocument,ORDER_LIST} from '../web/checkout-connector/order-audit.js';
import {CheckoutRpcPeer} from '../web/checkout-connector/checkout-rpc-peer.js';import {NativeCheckoutApi} from '../src/desktop/native-checkout-api.mjs';
import {DesktopCheckoutRuntime} from '../src/desktop/checkout-runtime.mjs';import {CHECKOUT_PLAN as P} from '../web/checkout-connector/checkout-rpc-contract.js';
import {merchantDocument} from '../web/checkout-connector/page-program.js';
import {createPurchaseRecord,TASK_KEY} from '../web/checkout-connector/job.js';
import {proDigest} from '../src/desktop/browser-session.mjs';
import {OrderAudit} from '../web/checkout-connector/order-audit.js';
import {createCheckoutNativeLink} from '../web/checkout-connector/checkout-native-link.js';
const {chromium}=createRequire(import.meta.url)(join(homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const ref='W123456789012',hash=createHash('sha256').update(ref).digest('hex'),detailUrl='https://secure10.www.apple.com.cn/shop/order/detail/FAKE/'+ref+'?_s=FAKE';
let server,browser,origin;
before(async()=>{server=http.createServer((q,r)=>r.end('FAKE C238'));await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-background-networking']});});
after(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));});
const list=(status='你的取货订单已取消。')=>`<div role="main" class="rs-ol"><h1>你已订购的产品。</h1><ul><li class="rs-ol-tile"><a data-autom="product-tile-name" aria-label="iPhone 18 Pro - Order ${ref}" aria-describedby="delivery" href="${detailUrl}">iPhone 18 Pro</a><div class="rs-ol-tile-delivery" id="delivery">${status}</div></li></ul><p class="rs-order-appleidsubheader">你当前登录的账户是 FAKE@example.invalid</p></div>`;
const detail=(status='你的取货订单已取消。')=>`<div role="main" class="rs-od-container"><h1>你的订单详情。</h1><div class="rs-od-order-number"><span>订单号：</span><span> ${ref}</span></div><div class="rs-od-itemdetail"><h3 class="rs-display-item-name">iPhone 18 Pro 256GB 黑色</h3><span class="rs-od-itemstatus">${status}</span></div><div class="rs-od-itempickup"><span class="rs-pickuplocation">Apple 大连恒隆广场</span></div><div data-autom="total-billing-summary-row"><span>总计 (含税)</span><span>RMB 9,999</span></div><button>继续使用支付宝支付</button></div>`;
async function world({newTabLag=0,detailLag=0}={}){
 const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort('blockedbyclient'));await context.routeWebSocket('**/*',s=>s.close());
 const page=await context.newPage();await page.goto(origin);let state='你的取货订单已取消。',url=ORDER_LIST,id=10,created=0,removed=0,writes=0;const pages=new Map(),lags=new Map();let staged=null;
 const render=async u=>{url=u;await page.setContent(/\/detail\//.test(u)?detail(state):list(state));};
 const raw={locks:{request:async(_n,_o,fn)=>fn({name:'FAKE-owner'})},permissions:{async contains(){return true;}},tabs:{async create(p){created++;pages.set(++id,p.url);lags.set(id,newTabLag);await render(p.url);return{id,status:'loading',url:p.url};},async get(t){if((lags.get(t)??0)>0){lags.set(t,lags.get(t)-1);return{id:t,status:'loading',url:'',pendingUrl:pages.get(t)};}if(staged?.id===t){if(staged.left-->0)return{id:t,status:'complete',url:pages.get(t)};pages.set(t,staged.url);await render(staged.url);staged=null;}return{id:t,status:'complete',url:pages.get(t)};},async update(t,p){if(p.url){if(detailLag>0)staged={id:t,url:p.url,left:detailLag};else{pages.set(t,p.url);await render(p.url);}}return {id:t,url:pages.get(t),status:'loading'};},async remove(t){pages.delete(t);removed++;}},scripting:{async executeScript(q){assert.ok([orderDocument,merchantDocument].includes(q.func));if(q.args[1])writes++;const result=await page.evaluate(({source,url,args})=>new Function('location','return ('+source+')')({href:url,pathname:new URL(url).pathname})(...args),{source:q.func.toString(),url,args:q.args});return [{frameId:0,documentId:'FAKE-doc',result}];}}};
 const peer=new CheckoutRpcPeer({api:raw,contextId:'FAKE-C238-order-actor',purchaseAllowed:true});const api=new NativeCheckoutApi({contextId:peer.contextId,exchange:q=>peer.receive(q)});
 return {context,page,peer,api,raw,render,seedReceipt:async()=>{url='https://secure10.www.apple.com.cn/shop/checkout/interstitial';pages.set(7,url);peer.tabs.set(7,{last:null,navigation:null});await page.setContent('<main><h1>你的订单正在等待付款。</h1><h2>iPhone 18 Pro 256GB 黑色</h2><a data-autom="order-number" href="https://www.apple.com.cn/xc/cn/vieworder/'+ref+'/FAKE@example.invalid">订单 #'+ref+'</a></main>');},setState:v=>state=v,counts:()=>({created,removed,writes}),read:kind=>raw.scripting.executeScript({func:orderDocument,args:[kind]})};
}
test('C238 rendered authenticated terminal list becomes clear, with no raw reference/account/link in native result',async()=>{const w=await world();try{const o=await w.api.auditOrders(P);assert.equal(o.state,'clear');assert.equal(o.authenticated,true);assert.equal(o.matchingCount,1);assert.ok(!JSON.stringify(o).includes(ref));assert.ok(!JSON.stringify(o).includes('example.invalid'));assert.ok(!JSON.stringify(o).includes('/detail/'));assert.deepEqual(w.counts(),{created:1,removed:1,writes:0});}finally{await w.context.close();}});
for(const [name,value,expected] of [['pending','请在 22 分钟内完成付款。','unpaid-exists'],['uncertain','正在处理','unconfirmed'],['collected','已取货 9月 17','clear']])test('C238 '+name+' account status',async()=>{const w=await world();try{w.setState(value);assert.equal((await w.api.auditOrders(P)).state,expected);}finally{await w.context.close();}});
for(const [name,change]of [['missing account',()=>document.querySelector('.rs-order-appleidsubheader').remove()],['empty not proven',()=>document.querySelector('li').remove()],['pagination',()=>document.querySelector('[role=main]').insertAdjacentHTML('beforeend','<button>下一页</button>')],['foreign link',()=>document.querySelector('a').href='https://evil.invalid/detail'],['status outside item',()=>document.querySelector('[role=main]').append(document.querySelector('#delivery'))],['hidden status',()=>document.querySelector('#delivery').hidden=true],['missing heading',()=>document.querySelector('h1').remove()]])test('C238 '+name+' never proves no pending orders',async()=>{const w=await world();try{await w.render(ORDER_LIST);await w.page.evaluate(change);assert.equal((await w.read('list'))[0].result.state,'unknown');}finally{await w.context.close();}});
test('C238 login is auth, never empty list or clear',async()=>{const w=await world();try{await w.render(ORDER_LIST);await w.page.setContent('<main><h1>查找你的订单。</h1><iframe id="aid-auth-widget-iFrame"></iframe></main>');assert.equal((await w.read('list'))[0].result.state,'auth');}finally{await w.context.close();}});
for(const status of ['你的取货订单已取消。','请在 22 分钟内完成付款。'])test('C238 same-reference native detail '+status,async()=>{const w=await world();try{w.setState(status);const o=await w.api.auditOrders(P,hash);assert.equal(o.state,'detail');assert.equal(o.status,status.includes('取消')?'cancelled':'unpaid');assert.equal(o.sameReference,true);assert.equal(o.productMatches,true);assert.equal(o.totalCny,9999);assert.equal(o.storeMatches,true);assert.equal(o.quantity,null);assert.equal(o.slot,null);assert.equal(JSON.stringify(o).includes(ref),false);assert.deepEqual(w.counts(),{created:1,removed:1,writes:0});}finally{await w.context.close();}});
test('C238 wrong expected reference never follows a different order',async()=>{const w=await world();try{assert.equal((await w.api.auditOrders(P,'f'.repeat(64))).state,'not-found');assert.equal(w.counts().removed,1);}finally{await w.context.close();}});
for(const executor of ['desktop','browser'])test('C238 '+executor+' sent final performs only native same-order audit, without ledger edits or a new buy',async()=>{const w=await world();try{const row={finalIntent:{sent:true},pending:{action:'submitOrder'},orderRefHash:hash},before=JSON.stringify(row);let writes=0;const runtime=new DesktopCheckoutRuntime({executor,ordersEnabled:true,store:{get:async()=>row,put:async()=>writes++},launch:async()=>{throw Error('No launch expected');}});Object.assign(runtime,{opened:true,api:w.api,lease:{owned:true}});const o=await runtime.execute({});assert.equal(o.orderCheck.status,'cancelled');assert.equal(o.pendingAction,'submitOrder');assert.equal(o.realOrderVerified,false);assert.equal(writes,0);assert.equal(JSON.stringify(row),before);}finally{await w.context.close();}});
test('C238 unconfirmed preflight never enters purchase runtime',async()=>{const w=await world();try{w.setState('正在处理');let writes=0;const runtime=new DesktopCheckoutRuntime({ordersEnabled:true,store:{get:async()=>({}),put:async()=>writes++},launch:async()=>{throw Error('No launch');}});Object.assign(runtime,{opened:true,api:w.api,lease:{owned:true}});const o=await runtime.execute({});assert.equal(o.orderCheck.state,'unconfirmed');assert.equal(writes,0);}finally{await w.context.close();}});
test('C238 reconnect retries are bounded, preserve the granted host and never request permissions',async()=>{let disconnect,connects=0;const timers=[];const api={permissions:{contains:async()=>true,request:async()=>assert.fail('No permission expansion')},runtime:{connectNative(name){assert.equal(name,'com.applebuy.checkout');connects++;return {onMessage:{addListener(){}},onDisconnect:{addListener(f){disconnect=f;}},disconnect(){},postMessage(){}};}}};const link=createCheckoutNativeLink(api,{schedule:(f,ms)=>{timers.push({f,ms});return timers.length;},cancel:()=>{}});await link.connect();for(let i=0;i<4;i++){disconnect();await new Promise(r=>setImmediate(r));if(timers[i]){timers[i].f();await new Promise(r=>setImmediate(r));}}assert.equal(connects,4);assert.deepEqual(timers.map(t=>t.ms),[1000,3000,8000]);link.stop();});
test('C238 detail with changed displayed identity or two item rows stays unknown',async()=>{const w=await world();try{await w.render(detailUrl);await w.page.evaluate(()=>document.querySelector('.rs-od-order-number').textContent='订单号： W999999999999');assert.equal((await w.read('detail'))[0].result.state,'unknown');await w.render(detailUrl);await w.page.evaluate(()=>{const e=document.querySelector('.rs-od-itemdetail');e.after(e.cloneNode(true));});assert.equal((await w.read('detail'))[0].result.state,'unknown');}finally{await w.context.close();}});
test('C238 cancelled detail without pickup or quantity does not invent either fact',async()=>{const w=await world();try{await w.render(detailUrl);await w.page.evaluate(()=>document.querySelector('.rs-od-itempickup').remove());const o=(await w.read('detail'))[0].result;assert.equal(o.status,'cancelled');assert.equal(o.store,null);assert.equal(o.quantity,null);}finally{await w.context.close();}});
test('C238 hashing while native content changes returns unknown',async()=>{const w=await world();try{await w.render(ORDER_LIST);await w.page.evaluate(()=>{const old=crypto.subtle.digest.bind(crypto.subtle);crypto.subtle.digest=async(...args)=>{const result=await old(...args);document.querySelector('#delivery').textContent='正在处理';return result;};});assert.equal((await w.read('list'))[0].result.state,'unknown');}finally{await w.context.close();}});
test('C238 paused or lost owner during order read cannot continue into buying',async()=>{for(const reason of ['pause','owner']){let finish,writes=0;const wait=new Promise(r=>finish=r),runtime=new DesktopCheckoutRuntime({ordersEnabled:true,store:{get:async()=>({}),put:async()=>writes++},launch:async()=>{throw Error('No launch');}});Object.assign(runtime,{opened:true,lease:{owned:true},api:{auditOrders:()=>wait}});const done=runtime.execute({});await new Promise(r=>setImmediate(r));if(reason==='pause')runtime.paused=true;else runtime.lease.owned=false;finish({state:'clear',authenticated:true,accountHash:'a'.repeat(64),matchingCount:1});await assert.rejects(done,/Cancelled/);assert.equal(writes,0);}});

// C240 regressions: the real RPC/renderer/controller chain starts with an uncommitted tab or a late receipt.
test('C240 waits for empty initial URL and old list after detail navigation before interpreting either document',async()=>{const w=await world({newTabLag:2,detailLag:2});try{const o=await w.api.auditOrders(P,hash);assert.equal(o.state,'detail');assert.equal(o.status,'cancelled');assert.equal(w.counts().writes,0);}finally{await w.context.close();}});
for(const executor of ['desktop','browser'])test('C240 '+executor+' originating late receipt is captured before same-order lookup without any second action',async()=>{const w=await world();try{await w.seedReceipt();let row={...createPurchaseRecord(P,{taskId:'FAKE-c240-task',planDigest:proDigest,tabId:7,now:Date.now(),id:()=>crypto.randomUUID()}),desktopContext:w.api.sessionId,bagAddStarted:true,resourceWritten:true,bagTotalCny:9999,finalIntent:{id:'FAKE-final-intent',sent:true},pending:{id:'FAKE-submit-command',action:'submitOrder',beforePhase:'REVIEW',documentId:'FAKE-review',deadline:Date.now()-1}};const rt=new DesktopCheckoutRuntime({executor,ordersEnabled:true,store:{get:async()=>structuredClone(row),put:async(k,v)=>{assert.equal(k,TASK_KEY);row=structuredClone(v);}},launch:async()=>{throw Error('No launch');}});Object.assign(rt,{opened:true,tabId:7,api:w.api,lease:{owned:true}});const o=await rt.advance({checkoutApproved:true,newContextConfirmed:true});assert.equal(row.orderRefHash,hash);assert.equal(o.orderCheck.status,'cancelled');assert.equal(row.pending.action,'submitOrder');assert.equal(row.finalIntent.sent,true);assert.equal(w.counts().writes,0);await assert.rejects(rt.submit({termsAccepted:true,existingOrdersChecked:true,noExtras:true}),/FinalConsent/);}finally{await w.context.close();}});
test('C240 foreign context without an original hash cannot bind a similar receipt',async()=>{const w=await world();try{await w.seedReceipt();const row={desktopContext:'FAKE-different-context',finalIntent:{sent:true},pending:{action:'submitOrder'},orderRefHash:null};let puts=0;const rt=new DesktopCheckoutRuntime({ordersEnabled:true,store:{get:async()=>row,put:async()=>puts++},launch:async()=>{throw Error('No launch');}});Object.assign(rt,{opened:true,tabId:7,api:w.api,lease:{owned:true}});const o=await rt.execute({});assert.equal(o.orderCheck.state,'reference-missing');assert.equal(row.orderRefHash,null);assert.equal(puts,0);assert.equal(w.counts().created,0);}finally{await w.context.close();}});
test('C240 retained auth tab is focused once and its loading state does not create or close another tab',async()=>{let active=0,created=0,removed=0,now=0,readState='auth';const peer={tabs:new Map()},audit=new OrderAudit(peer,{now:()=>now,wait:async()=>{}});const api={permissions:{contains:async()=>true},tabs:{create:async()=>{created++;return{id:7};},get:async()=>({url:ORDER_LIST,status:'complete'}),update:async()=>active++,remove:async()=>removed++}};audit.read=async()=>({state:readState});assert.equal((await audit.run(api,P)).state,'auth');assert.equal((await audit.run(api,P)).state,'auth');readState='loading';assert.equal((await audit.run(api,P)).state,'waiting');assert.equal(created,1);assert.equal(removed,0);assert.equal(active,1);now=300001;assert.equal((await audit.run(api,P)).state,'unknown');assert.equal(removed,0);});
test('C240 generic native getTab cannot expose an account/order path from a private audit tab',async()=>{const w=await world();try{const id=(await w.raw.tabs.create({url:ORDER_LIST})).id;w.peer.tabs.set(id,{orderAudit:true,last:null});await assert.rejects(w.api.tabs.get(id),/ResultUnconfirmed/);}finally{await w.context.close();}});
test('C240 stop while native permission check is pending prevents a later connection',async()=>{let finish,connects=0;const link=createCheckoutNativeLink({permissions:{contains:()=>new Promise(r=>finish=r)},runtime:{connectNative:()=>{connects++;throw Error('must not connect');}}});const p=link.connect();await new Promise(r=>setImmediate(r));link.stop();finish(true);assert.equal((await p).connected,false);assert.equal(connects,0);});
test('C242 known closed login tab clears only local tab metadata and permits a later fresh query',async()=>{let gone=false,created=6;const peer={tabs:new Map()},audit=new OrderAudit(peer,{wait:async()=>{}});audit.read=async()=>({state:'auth'});const api={permissions:{contains:async()=>true},tabs:{create:async()=>({id:++created}),get:async id=>{if(gone)throw Error('No tab with id: '+id+'.');return{url:ORDER_LIST,status:'complete'};},update:async()=>{},remove:async id=>{if(gone)throw Error('No tab with id: '+id+'.');}}};await audit.run(api,P);gone=true;assert.equal((await audit.run(api,P)).state,'unknown');assert.equal(audit.tabId,null);assert.equal(audit.authUntil,null);assert.equal(peer.tabs.size,0);gone=false;assert.equal((await audit.run(api,P)).state,'auth');assert.equal(audit.tabId,8);});
test('C242 ambiguous tab permission failure is not reported as a disappeared or cleaned tab',async()=>{let denied=false;const peer={tabs:new Map()},audit=new OrderAudit(peer,{wait:async()=>{}});audit.read=async()=>({state:'auth'});const api={permissions:{contains:async()=>true},tabs:{create:async()=>({id:7}),get:async()=>{if(denied)throw Error('Permission denied');return{url:ORDER_LIST,status:'complete'};},update:async()=>{},remove:async()=>{if(denied)throw Error('Permission denied');}}};await audit.run(api,P);denied=true;await assert.rejects(audit.run(api,P),/Permission denied/);assert.equal(audit.tabId,7);assert.equal(peer.tabs.has(7),true);});
test('C242 observed removal touches owned tabs only and disposes the listener on close',async()=>{const listeners=new Set(),api={tabs:{onRemoved:{addListener:f=>listeners.add(f),removeListener:f=>listeners.delete(f)},remove:async()=>{}}},peer=new CheckoutRpcPeer({api,contextId:'FAKE-C242-event-context'});peer.orderAudit=new OrderAudit(peer);peer.orderAudit.tabId=7;peer.tabs.set(7,{orderAudit:true});for(const f of listeners)f(99);assert.equal(peer.tabs.size,1);for(const f of listeners)f(7);assert.equal(peer.tabs.size,0);assert.equal(peer.orderAudit.tabId,null);await peer.operation('closeSession',{});assert.equal(listeners.size,0);assert.equal(peer.closed,true);});
test('C242 closeSession accepts a positively already-removed owned tab but no generic failure',async()=>{for(const known of [true,false]){const peer=new CheckoutRpcPeer({api:{tabs:{remove:async()=>{throw Error(known?'No tab with id: 7.':'Permission denied');}}},contextId:'FAKE-C242-close-context'});peer.tabs.set(7,{orderAudit:true});if(known){assert.deepEqual(await peer.operation('closeSession',{}),{closed:true});assert.equal(peer.tabs.size,0);}else{await assert.rejects(peer.operation('closeSession',{}),/Permission denied/);assert.equal(peer.closed,false);assert.equal(peer.tabs.size,1);}}});
