// Real runtime/native facade and peer, entirely FAKE merchant/API/owner. No website or customer data.
import test from 'node:test';import assert from 'node:assert/strict';import {world} from './fixtures/c121-native-world.mjs';
import {bagPlanCheck,safeCheckoutDiagnostic} from '../src/desktop/checkout-diagnostic.mjs';import {PRO_PLAN} from '../src/desktop/browser-session.mjs';
for(const [name,quantity]of [['matching singleton',1],['two pieces',2]])test('C160 observe reports '+name+' without authority, writes or purchase actions',async()=>{
 const f=world();f.w.phase='BAG';f.w.mergedQuantity=quantity;const before=structuredClone(f.w.row);
 try{const r=await f.runtime.open();assert.equal(r.bagCheck?.schema,'applebuy-bag-check/v1');assert.equal(r.bagCheck.quantity,quantity);assert.equal(r.bagCheck.totalCny,9999*quantity);assert.equal(r.bagCheck.modelMatches,true);assert.equal(r.bagCheck.capacityMatches,true);assert.equal(r.bagCheck.colorMatches,true);assert.equal(r.bagCheck.matchesPlan,quantity===1);assert.equal(r.realOrderVerified,false);assert.equal(f.w.writes,0);assert.deepEqual(f.w.commands,[]);assert.deepEqual(f.w.row,before);}finally{await f.runtime.close();}
});
test('C160 AUTH exposes no bag snapshot and creates no authority or record',async()=>{const f=world();f.w.phase='AUTH';try{const r=await f.runtime.open();assert.equal(r.bagCheck,null);assert.equal(r.realOrderVerified,false);assert.equal(f.w.writes,0);assert.deepEqual(f.w.commands,[]);}finally{await f.runtime.close();}});
test('C160 malformed and customer-bearing inputs produce only closed bounded scalars',()=>{const out=bagPlanCheck({phase:'BAG',verifiedStep:false,extras:null,purchase:{model:'FAKE-secret-model',capacity:'FAKE-secret',color:'FAKE-secret',quantity:'FAKE-private',totalCny:Infinity,email:'FAKE-person@example.invalid',password:'FAKE-private-password'}},PRO_PLAN);assert.equal(out.quantity,null);assert.equal(out.totalCny,null);assert.equal(out.matchesPlan,false);assert.equal(out.extrasClear,false);assert.equal(JSON.stringify(out).includes('FAKE'),false);assert.equal(bagPlanCheck({phase:'DETAILS',purchase:{password:'FAKE-private'}},PRO_PLAN),null);});
test('C160 only declared diagnostic errors can cross the worker boundary',()=>{assert.equal(safeCheckoutDiagnostic(Error('DesktopTransferNeedsCurrentMatchingSingleton')),'DesktopTransferNeedsCurrentMatchingSingleton');for(const message of ['FAKE-secret-password','https://example.invalid/FAKE-auth?private=secret','FAKE-person@example.invalid'])assert.equal(safeCheckoutDiagnostic(Error(message)),'CheckoutResultUnconfirmed');});
