import test from 'node:test';import assert from 'node:assert/strict';
import {restartFromCurrentEmpty} from '../src/desktop/empty-restart.mjs';import {PRO_PLAN,proDigest,runDesktopSession} from '../src/desktop/browser-session.mjs';import {createPurchaseRecord,TASK_KEY} from '../web/checkout-connector/job.js';
function fixture(){const original={...createPurchaseRecord(PRO_PLAN,{taskId:'FAKE-root',planDigest:proDigest,tabId:99,now:0,id:()=> 'FAKE'}),state:'NEEDS_VERIFICATION',pending:{action:'addBag',id:'FAKE-unknown',documentId:'FAKE-old',deadline:0},bagAddStarted:true,resourceWritten:true};const w={row:{...structuredClone(original),reconcileOnly:true,desktopHandoff:{schema:'applebuy-desktop-handoff/v1',id:'FAKE-handoff',originalSnapshot:structuredClone(original)}},writes:0};const store={async get(){return structuredClone(w.row);},async put(k,v){assert.equal(k,TASK_KEY);w.writes++;w.row=structuredClone(v);},async acquireOwner(){return {owned:true,release:async()=>{}};}};const api={sessionId:'FAKE-C130-one',tabs:{async get(){return {id:7,url:'https://www.apple.com.cn/shop/bag',status:'complete'};}},permissions:{async contains(){return true;}},scripting:{async executeScript(q){assert.equal(q.args.length,1);return [{frameId:0,documentId:'FAKE-current-empty',result:{schema:'applebuy-merchant-read/v1',phase:'EMPTY_BAG',path:'/shop/bag',verifiedStep:true}}];}}};return {w,store,api};}
const approved={approved:true,accountConfirmedByUser:true,oldCheckoutStoppedByUser:true,existingOrdersCheckedByUser:true,tabId:7};
test('C130 interrupted pre-Add successor can create a bounded new generation after readonly reconcile; original unknown remains exact',async()=>{
 const f=fixture();await restartFromCurrentEmpty({...f,...approved});const first=structuredClone(f.w.row);const nextApi={...f.api,sessionId:'FAKE-C130-two'};await runDesktopSession({store:f.store,api:nextApi,tabId:7,mode:'reconcile'});assert.equal(f.w.row.reconcileOnly,true);const stopped=structuredClone(f.w.row);const next=await restartFromCurrentEmpty({...f,api:nextApi,...approved});assert.equal(next.created,true);assert.equal(f.w.row.desktopEmptyRestart.generation,2);assert.deepEqual(f.w.row.desktopEmptyRestart.originalTask,stopped);assert.deepEqual(f.w.row.desktopEmptyRestart.originalTask.desktopEmptyRestart.originalTask,first.desktopEmptyRestart.originalTask);
});
test('C130 an expired same-context successor before Add can be explicitly superseded, with no source revival',async()=>{
 const f=fixture();await restartFromCurrentEmpty({...f,...approved});f.w.row.expiresAt=0;const stopped=structuredClone(f.w.row);const result=await restartFromCurrentEmpty({...f,...approved});assert.equal(result.created,true);assert.deepEqual(f.w.row.desktopEmptyRestart.originalTask,stopped);assert.equal(f.w.row.desktopEmptyRestart.generation,2);
});
test('C130 chain is capped at three generations and cannot hide any later final or archive tamper',async()=>{
 const f=fixture();for(let generation=1;generation<=3;generation++){await restartFromCurrentEmpty({...f,...approved});assert.equal(f.w.row.desktopEmptyRestart.generation,generation);f.w.row.expiresAt=0;}
 const before=structuredClone(f.w.row),writes=f.w.writes;await assert.rejects(restartFromCurrentEmpty({...f,...approved}));assert.equal(f.w.writes,writes);assert.deepEqual(f.w.row,before);
 const bad=fixture();await restartFromCurrentEmpty({...bad,...approved});bad.w.row.reconcileOnly=true;bad.w.row.desktopEmptyRestart.originalTask.finalIntent={id:'FAKE-final-hidden',sent:true};const badWrites=bad.w.writes;await assert.rejects(restartFromCurrentEmpty({...bad,...approved}));assert.equal(bad.w.writes,badWrites);
});
