// Exact stopped post-payment FAKE source through the real archive/validation chain. No personal ledger/browser access.
import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,FLAGS} from './fixtures/c185-ended-world.mjs';
import {renewEndedDraft} from '../src/desktop/ended-draft.mjs';
import {restartExpiredPayment} from '../src/desktop/expired-payment-restart.mjs';
import {restartExpiredReview,validateExpiredReviewRestart,expiredReviewSourceShape,additionalExpiredReviewSourceShape} from '../src/desktop/expired-review-restart.mjs';
import {CONTACT_SLOT_BASIS,canonicalJson,PurchaseJob} from '../web/checkout-connector/job.js';
import {PRO_PLAN,proDigest} from '../src/desktop/browser-session.mjs';
import {CHECKOUT_EXECUTOR_VERSION} from '../web/checkout-connector/page-program.js';
import {DesktopTaskStore} from '../src/desktop/task-store.mjs';
import {mkdtemp,rm,unlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,sep} from 'node:path';
import {TASK_KEY} from '../web/checkout-connector/job.js';
const OPTIONS={approved:true,newContextConfirmed:true,oldExecutorStopped:true,sameAccountOrdersClear:true,expiredCheckoutUrl:'https://secure10.www.apple.com.cn/shop/checkout'};
async function world(){
 const f=await fixture();await renewEndedDraft({...f,...FLAGS});const {w,api}=f;
 const stage=(action)=>Object.assign(w.row,{state:'NEEDS_VERIFICATION',expiresAt:0,bagAddStarted:true,resourceWritten:true,bagTotalCny:9999,pending:{id:'FAKE-pending',action,beforePhase:action==='fillDetails'?'DETAILS':'PAYMENT',...(action==='fillDetails'?{contactOnly:true}:{paymentOnly:true}),documentId:'FAKE-before',deadline:0},acceptedSlot:{date:'October 7',start:'21:15',end:'21:30',verified:true,basis:CONTACT_SLOT_BASIS},history:[{event:'slot-continued-to-contact-only-details',readSequence:1}]});
 stage('fillDetails');api.sessionId='FAKE-payment-recovery';const get=api.tabs.get,execute=api.scripting.executeScript;w.probes=0;w.expired=true;w.closed=0;
 api.executorVersion=async()=>CHECKOUT_EXECUTOR_VERSION;api.createExpiryProbe=async()=>{w.probes++;return {id:88};};
 api.tabs.get=async id=>id===88?{status:'complete',url:'https://www.apple.com.cn/shop/sorry/session_expired'}:get(id);
 api.tabs.remove=async id=>{assert.equal(id,88);w.closed++;};
 api.scripting.executeScript=async q=>q.target.tabId===88?[{frameId:0,documentId:'FAKE-expired',result:{schema:'applebuy-merchant-read/v1',phase:'UNKNOWN',path:'/shop/sorry/session_expired',verifiedStep:false,...(w.expired?{merchantError:'session-expired'}:{})}}]:execute(q);
 await restartExpiredPayment({...f,...OPTIONS});stage('continuePayment');api.sessionId='FAKE-post-review-context';w.probes=0;w.closed=0;return f;
}

async function secondWorld(){const f=await world();await restartExpiredReview({...f,...OPTIONS});Object.assign(f.w.row,{state:'NEEDS_VERIFICATION',expiresAt:0,bagAddStarted:true,resourceWritten:true,bagTotalCny:9999,pending:{id:'FAKE-generation1-payment',action:'continuePayment',beforePhase:'PAYMENT',paymentOnly:true,documentId:'FAKE-current',deadline:0},acceptedSlot:{date:'October 7',start:'21:15',end:'21:30',verified:true,basis:CONTACT_SLOT_BASIS},history:[{event:'slot-continued-to-contact-only-details',readSequence:1}]});f.api.sessionId='FAKE-one-additional-context';f.w.probes=0;return f;}
test('C229 default original entry refuses a consumed review source; explicit one extra opportunity preserves complete archive and restrictions',async()=>{const f=await secondWorld(),old=structuredClone(f.w.row);assert.equal(additionalExpiredReviewSourceShape(old),true);await assert.rejects(restartExpiredReview({...f,...OPTIONS}),/SourceUnconfirmed/);assert.equal(f.w.probes,0);await restartExpiredReview({...f,...OPTIONS,additionalRecoveryApproved:true});const r=f.w.row;assert.equal(r.desktopReviewRestart.generation,2);assert.ok(await validateExpiredReviewRestart(r,f.api,f.store));assert.equal(canonicalJson(await f.store.readArchive(r.desktopReviewRestart.sourceArchive)),canonicalJson(old));for(const k of ['initialDates','floors','dateCursor','refusals','rejected'])assert.deepEqual(r[k],old[k]);assert.equal(r.acceptedSlot,null);assert.equal(r.finalIntent,null);assert.deepEqual(f.w.commands,[]);});
test('C229 generation two cannot receive a third recovery, even with another true confirmation',async()=>{const f=await secondWorld();await restartExpiredReview({...f,...OPTIONS,additionalRecoveryApproved:true});Object.assign(f.w.row,{state:'NEEDS_VERIFICATION',expiresAt:0,bagAddStarted:true,resourceWritten:true,bagTotalCny:9999,pending:{id:'FAKE-second-payment',action:'continuePayment',beforePhase:'PAYMENT',paymentOnly:true,documentId:'FAKE-current',deadline:0},acceptedSlot:{date:'October 7',start:'21:15',end:'21:30',verified:true,basis:CONTACT_SLOT_BASIS},history:[{event:'slot-continued-to-contact-only-details',readSequence:1}]});f.api.sessionId='FAKE-third-refused';const before=canonicalJson(f.w.row),probes=f.w.probes;assert.equal(additionalExpiredReviewSourceShape(f.w.row),false);await assert.rejects(restartExpiredReview({...f,...OPTIONS,additionalRecoveryApproved:true}),/SourceUnconfirmed/);assert.equal(canonicalJson(f.w.row),before);assert.equal(f.w.probes,probes);});
for(const [name,edit]of [['final',r=>r.finalIntent={id:'FAKE-final',sent:true}],['final history',r=>r.history.push({event:'final-unknown'})],['reference',r=>r.orderRefHash='a'.repeat(64)],['active deadline',r=>r.expiresAt=Date.now()+999999],['wrong pending',r=>r.pending.action='fillDetails'],['wrong floor',r=>r.floors['October 7']='21:00'],['missing earlier archive',r=>r.desktopReviewRestart.sourceBackup.data='FAKE-corrupt']])test('C229 '+name+' refuses the extra opportunity before new resource intent',async()=>{const f=await secondWorld();edit(f.w.row);const before=canonicalJson(f.w.row),writes=f.w.writes;await assert.rejects(restartExpiredReview({...f,...OPTIONS,additionalRecoveryApproved:true}),/SourceUnconfirmed/);assert.equal(canonicalJson(f.w.row),before);assert.equal(f.w.writes,writes);assert.equal(f.w.probes,0);assert.deepEqual(f.w.commands,[]);});
test('C229 missing merchant expiry and mismatched bag remain hard stops',async()=>{const f=await secondWorld(),before=canonicalJson(f.w.row);f.w.expired=false;await assert.rejects(restartExpiredReview({...f,...OPTIONS,additionalRecoveryApproved:true}),/MerchantExpiryUnconfirmed/);f.w.expired=true;f.w.quantity=2;await assert.rejects(restartExpiredReview({...f,...OPTIONS,additionalRecoveryApproved:true}),/BagUnconfirmed/);assert.equal(canonicalJson(f.w.row),before);});
test('C229 extra-generation marker cannot be forged or source backup changed',async()=>{const f=await secondWorld();await restartExpiredReview({...f,...OPTIONS,additionalRecoveryApproved:true});const good=structuredClone(f.w.row);for(const edit of [r=>delete r.desktopReviewRestart.additionalRecoveryApproved,r=>r.desktopReviewRestart.generation=3,r=>r.desktopReviewRestart.generation=1,r=>r.desktopReviewRestart.sourceBackup.data='FAKE']){const r=structuredClone(good);edit(r);assert.equal(await validateExpiredReviewRestart(r,f.api,f.store),null);}assert.ok(await validateExpiredReviewRestart(good,f.api,f.store));});

import {DesktopCheckoutRuntime} from '../src/desktop/checkout-runtime.mjs';
test('C229 actual runtime additional recovery reuses singleton bag and performs one FAKE checkout to REVIEW without Add/final',async()=>{const f=await secondWorld(),runtime=new DesktopCheckoutRuntime({store:f.store,launch:async()=>({api:f.api,close:async()=>{}})});try{await runtime.open();const result=await runtime.restartPayment({...OPTIONS,additionalRecoveryApproved:true});assert.equal(result.phase,'REVIEW');assert.equal(f.w.row.desktopReviewRestart.generation,2);assert.equal(f.w.commands.filter(c=>c==='checkout').length,1);assert.equal(f.w.commands.includes('addBag'),false);assert.equal(f.w.commands.includes('submitOrder'),false);assert.equal(f.w.row.finalIntent,null);}finally{await runtime.close();}});
test('C229 real kernel-held store retains generation-one and earlier archives with an identical backup',async()=>{const f=await secondWorld(),dir=await mkdtemp(join(tmpdir(),'applebuy-c229-')),file=join(dir,'task.json'),store=new DesktopTaskStore(file),lease=await store.acquireOwner();try{for(const old of f.w.archives.values())await store.archiveSnapshot(old);await store.put(TASK_KEY,f.w.row);const before=canonicalJson(f.w.row);await restartExpiredReview({...f,store,...OPTIONS,additionalRecoveryApproved:true});const r=await store.get(TASK_KEY);assert.equal(canonicalJson(await store.readArchive(r.desktopReviewRestart.sourceArchive)),before);assert.ok(await validateExpiredReviewRestart(r,f.api,store));await unlink(join(file+'.archives',r.desktopReviewRestart.sourceArchive+'.json'));assert.ok(await validateExpiredReviewRestart(r,f.api,store));}finally{await lease.release();assert.ok(resolve(dir).startsWith(resolve(tmpdir())+sep+'applebuy-c229-'));await rm(dir,{recursive:true});}});
