// Whole production source-shaped recovery with FAKE API/approval/account/merchant facts. No personal state.
import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {PRO_PLAN,proDigest,runDesktopSession} from '../src/desktop/browser-session.mjs';import {TASK_KEY,createPurchaseRecord,canonicalJson,PurchaseJob} from '../web/checkout-connector/job.js';
import {transferExistingCart,transferExpiredContactOnce,stoppedCheckoutDraftSource} from '../src/desktop/cart-transfer.mjs';
import {renewEndedDraft,validateEndedDraft,SHOP_HOST_SCOPE} from '../src/desktop/ended-draft.mjs';
import {DesktopCheckoutRuntime} from '../src/desktop/checkout-runtime.mjs';
const FLAGS={approved:true,newContextConfirmed:true,merchantExpiryConfirmed:true,oldExecutorStopped:true,sameAccountOrdersClear:true};const TERMS='https://www.apple.com.cn/shop/open/salespolicies';const hash=r=>createHash('sha256').update(canonicalJson(r)).digest('hex');
async function fixture(){
 const original={...createPurchaseRecord(PRO_PLAN,{taskId:'FAKE-base',planDigest:proDigest,tabId:9,now:0,id:()=> 'FAKE'}),state:'NEEDS_VERIFICATION',bagAddStarted:true,resourceWritten:true};
 const w={row:{...structuredClone(original),reconcileOnly:true,desktopHandoff:{schema:'applebuy-desktop-handoff/v1',id:'FAKE-HDF',originalSnapshot:structuredClone(original)}},phase:'BAG',writes:0,archives:new Map(),commands:[],host:true,quantity:1,total:9999,doc:'FAKE-bag',reads:0,slot:null,payment:null,ref:null};
 const store={get:async()=>structuredClone(w.row),put:async(k,v)=>{assert.equal(k,TASK_KEY);w.writes++;w.row=structuredClone(v);if(w.afterPut)w.afterPut();},acquireOwner:async()=>({owned:true,release:async()=>{}}),archiveSnapshot:async r=>{const d=hash(r);w.archives.set(d,structuredClone(r));return d;},readArchive:async d=>{if(!w.archives.has(d))throw Error('Archive missing');return structuredClone(w.archives.get(d));}};
 const api={sessionId:'FAKE-one',create:async()=>({id:7}),tabs:{get:async()=>({id:7,status:'complete',url:'https://www.apple.com.cn/shop/bag'}),update:async()=>{w.phase='ORDER_DETAIL';}},permissions:{contains:async p=>p.origins[0]===SHOP_HOST_SCOPE?w.host:true},scripting:{executeScript:async q=>{const cmd=q.args[1];if(cmd){w.commands.push(cmd.action);if(cmd.action==='checkout')w.phase='FULFILLMENT';else if(cmd.action==='selectPickup')w.phase='SLOTS';else if(cmd.action==='chooseSlot'){w.slot={date:cmd.date,start:cmd.start,end:cmd.end,verified:true};w.phase='DETAILS';}else if(cmd.action==='fillDetails')w.phase='PAYMENT';else if(cmd.action==='selectPayment')w.payment='支付宝';else if(cmd.action==='continuePayment')w.phase='REVIEW';else if(cmd.action==='submitOrder'){w.ref='c'.repeat(64);w.phase='ORDER_RECEIPT';}else throw Error('No Add or product configuration');return [{frameId:0,documentId:w.doc,result:{delivered:true}}];}w.reads++;if(w.onRead)w.onRead(w);const p={...PRO_PLAN.product,quantity:w.quantity,totalCny:w.total,itemVerified:true,verified:true,fulfillment:'pickup',store:PRO_PLAN.stores[0]},r={schema:'applebuy-merchant-read/v1',phase:w.phase,path:'/shop/bag',verifiedStep:true,purchase:p,extras:false,slotSummary:w.slot,acceptedSlot:w.slot,paymentMethod:w.payment,termsLinks:[TERMS],receiptVerified:!!w.ref,orderRefHash:w.ref,orderDetailLink:w.ref?'https://www.apple.com.cn/shop/order/detail/FAKE/FAKE':null};if(w.phase==='FULFILLMENT'){p.fulfillment=null;r.fulfillmentChoice='unselected';}if(w.phase==='SLOTS'){r.listComplete=true;r.dates=[{label:'October 7',ref:'date:0',enabled:true,selected:true}];r.selectedDate='October 7';r.times=[{start:'21:00',end:'21:15',ref:'slot:45',enabled:true},{start:'21:15',end:'21:30',ref:'slot:46',enabled:true}];}return [{frameId:0,documentId:w.doc,result:r}];}}};
 for(let n=1;n<=3;n++){api.sessionId='FAKE-'+n;w.row.reconcileOnly=true;w.row.expiresAt=0;await transferExistingCart({store,api,tabId:7,approved:true,newContextConfirmed:true});}
 w.row.state='NEEDS_VERIFICATION';w.row.reconcileOnly=true;w.row.expiresAt=0;w.row.pending={action:'fillDetails',id:'FAKE-contact',documentId:'FAKE-old',beforePhase:'DETAILS',deadline:0};w.row.bagAddStarted=true;w.row.resourceWritten=true;w.row.acceptedSlot={date:'October 7',start:'21:15',end:'21:30',verified:true};w.row.initialDates=['October 7','October 8'];w.row.floors={'October 7':'21:15'};api.sessionId='FAKE-four';await transferExpiredContactOnce({store,api,tabId:7,approved:true,newContextConfirmed:true,merchantExpiryConfirmed:true,oldCheckoutStopped:true,sameAccountOrdersChecked:true});
 w.row.state='NEEDS_USER';w.row.expiresAt=0;w.row.pending={action:'checkout',id:'FAKE-expired-checkout',documentId:'FAKE-before',beforePhase:'BAG',deadline:0};w.row.bagAddStarted=true;w.row.resourceWritten=true;api.sessionId='FAKE-renewed-context';w.reads=0;return {w,store,api,tabId:7};
}
test('C183 no fifth transfer; one explicit ended-draft renewal archives the exact source and reaches one FAKE unpaid without Add',async()=>{const f=await fixture(),before=structuredClone(f.w.row);assert.ok(stoppedCheckoutDraftSource(before));await assert.rejects(transferExistingCart({...f,approved:true,newContextConfirmed:true}));await renewEndedDraft({...f,...FLAGS});assert.deepEqual(f.w.archives.get(hash(before)),before);assert.ok(await validateEndedDraft(f.w.row,f.api,f.store));assert.ok(canonicalJson(f.w.row).length<canonicalJson(before).length);assert.deepEqual(f.w.row.initialDates,before.initialDates);assert.deepEqual(f.w.row.floors,before.floors);assert.equal(f.w.row.acceptedSlot,undefined);await assert.rejects(new PurchaseJob({store:f.store,port:{}}).retire(),/RevokedSource/);
 const a={checkoutApproved:true,newContextConfirmed:true,legacyOwnershipRevoked:true,planDigest:proDigest};const r=await runDesktopSession({...f,mode:'purchase',authority:a});assert.equal(r.phase,'REVIEW');assert.equal(r.realOrderVerified,false);assert.equal(f.w.commands.includes('addBag'),false);assert.equal(f.w.commands.filter(x=>x==='checkout').length,1);const last=await runDesktopSession({...f,mode:'purchase',authority:{...a,finalConsent:{taskId:f.w.row.taskId,documentId:f.w.row.lastDocumentId,termsUrl:TERMS,termsAccepted:true,existingOrdersChecked:true,noExtras:true,acceptedAt:Date.now()}}});assert.equal(last.state,'CONFIRMED_UNPAID');assert.equal(f.w.commands.filter(x=>x==='submitOrder').length,1);
});
for(const name of Object.keys(FLAGS))test('C183 missing '+name+' creates neither archive nor active record',async()=>{const f=await fixture(),writes=f.w.writes;await assert.rejects(renewEndedDraft({...f,...FLAGS,[name]:false}));assert.equal(f.w.archives.size,0);assert.equal(f.w.writes,writes);assert.deepEqual(f.w.commands,[]);});
for(const [name,change] of [['missing host scope',f=>f.w.host=false],['empty bag',f=>f.w.phase='EMPTY_BAG'],['two units',f=>f.w.quantity=2],['over cap',f=>f.w.total=10000],['unknown slot',f=>f.w.row.pending.action='chooseSlot'],['accepted current slot',f=>f.w.row.acceptedSlot={date:'October 7',start:'21:15',end:'21:30'}],['unknown final',f=>{f.w.row.pending.action='submitOrder';f.w.row.finalIntent={id:'FAKE-final',sent:true};}],['hidden current final',f=>f.w.row.other={finalIntent:{id:'FAKE-hidden',sent:true}}],['original window active',f=>f.w.row.expiresAt=Date.now()+60000],['changed document',f=>f.w.onRead=w=>{if(w.reads===2)w.doc='FAKE-replaced';}],['changed source',f=>f.w.onRead=w=>{if(w.reads===2)w.row.lastRead++;}]])test('C183 '+name+' denies without a new active record',async()=>{const f=await fixture();change(f);const writes=f.w.writes;await assert.rejects(renewEndedDraft({...f,...FLAGS}));assert.equal(f.w.writes,writes);assert.deepEqual(f.w.commands,[]);});
test('C183 missing/tampered archive or cleared marker cannot enable buying; second draft renewal is forbidden',async()=>{const f=await fixture();await renewEndedDraft({...f,...FLAGS});await assert.rejects(renewEndedDraft({...f,...FLAGS}));const d=f.w.row.desktopEndedDraft.sourceArchive,old=f.w.archives.get(d);f.w.archives.delete(d);assert.equal(await validateEndedDraft(f.w.row,f.api,f.store),null);f.w.archives.set(d,{...old,other:{finalIntent:{id:'FAKE-tamper',sent:true}}});assert.equal(await validateEndedDraft(f.w.row,f.api,f.store),null);f.w.archives.set(d,old);delete f.w.row.desktopEndedDraft;await assert.rejects(runDesktopSession({...f,mode:'purchase',authority:{checkoutApproved:true,newContextConfirmed:true,legacyOwnershipRevoked:true,planDigest:proDigest}}));assert.deepEqual(f.w.commands,[]);});
test('C183 lost owner/live approval during the second observation sends no action and writes no new record',async()=>{const f=await fixture(),writes=f.w.writes;let live=true;f.w.onRead=w=>{if(w.reads===2)live=false;};await assert.rejects(renewEndedDraft({...f,...FLAGS,live:()=>live}));assert.equal(f.w.writes,writes);assert.deepEqual(f.w.commands,[]);});
test('C183 runtime reports a durable transition after concurrent pause without performing Checkout',async()=>{const f=await fixture();let closed=false;const runtime=new DesktopCheckoutRuntime({store:f.store,launch:async()=>({api:f.api,close:async()=>{closed=true;}})});try{await runtime.open();f.w.afterPut=()=>{runtime.paused=true;};const r=await runtime.renewDraft(FLAGS);assert.equal(r.localTransitionCreated,true);assert.equal(r.state,'PAUSED');assert.deepEqual(f.w.commands,[]);assert.ok(f.w.row.desktopEndedDraft);}finally{await runtime.close();}assert.equal(closed,true);});
