// Actual private archive filesystem and production kernel holder, only owned FAKE test paths/data.
import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,mkdtemp,readFile,writeFile,rm,unlink,symlink} from 'node:fs/promises';import {resolve,join,relative} from 'node:path';import {createHash} from 'node:crypto';
import {DesktopTaskStore} from '../src/desktop/task-store.mjs';import {PRO_PLAN,proDigest} from '../src/desktop/browser-session.mjs';import {createPurchaseRecord,canonicalJson} from '../web/checkout-connector/job.js';
const parent=resolve('.local/test-runs');
async function fixture(run){await mkdir(parent,{recursive:true});const dir=await mkdtemp(join(parent,'c183-archive-'));const store=new DesktopTaskStore(join(dir,'task.json'));const row={...createPurchaseRecord(PRO_PLAN,{taskId:'FAKE-archive',planDigest:proDigest,tabId:7,now:0,id:()=> 'FAKE'}),unknownBranch:{pending:{action:'chooseSlot',value:'FAKE-no-customer'}},syntheticPadding:'FAKE'.repeat(100000)};let lease;try{lease=await store.acquireOwner();await run({dir,store,row,lease});}finally{await lease?.release();assert.ok(relative(parent,dir)&&!relative(parent,dir).startsWith('..'));await rm(dir,{recursive:true,force:true});}}
test('C183 physical archive is canonical/full/durable, replay is identical and actual ledger stays absent',async()=>fixture(async({dir,store,row})=>{const d=await store.archiveSnapshot(row),file=join(dir,'task.json.archives',d+'.json'),bytes=await readFile(file);assert.equal(createHash('sha256').update(bytes).digest('hex'),d);assert.equal(bytes.toString('utf8'),canonicalJson(row));assert.deepEqual(await store.readArchive(d),row);assert.equal(await store.archiveSnapshot(row),d);assert.equal(await store.get('applebuy-single-personal-purchase/v1'),null);}));
test('C183 missing/tampered archive and path traversal fail closed without overwriting a stored archive',async()=>fixture(async({dir,store,row})=>{const d=await store.archiveSnapshot(row),file=join(dir,'task.json.archives',d+'.json');await assert.rejects(store.readArchive('../outside'));await assert.rejects(store.readArchive('0'.repeat(64)));await writeFile(file,'FAKE tampered');await assert.rejects(store.readArchive(d));await assert.rejects(store.archiveSnapshot(row));assert.equal(await readFile(file,'utf8'),'FAKE tampered');}));
test('C183 oversized archive is rejected before directory/write, and released owner cannot create or read it',async()=>fixture(async({store,row,lease})=>{await assert.rejects(store.archiveSnapshot({...row,syntheticPadding:'x'.repeat(16000001)}));await lease.release();await assert.rejects(store.archiveSnapshot(row));await assert.rejects(store.readArchive('0'.repeat(64)));}));
test('C183 managed archive directory cannot be redirected through a real Windows junction or POSIX symlink',async()=>fixture(async({dir,store,row})=>{const outside=join(dir,'outside'),archive=join(dir,'task.json.archives');await mkdir(outside);await symlink(outside,archive,process.platform==='win32'?'junction':'dir');try{await assert.rejects(store.archiveSnapshot(row));}finally{await unlink(archive);}}));
