// Exact stopped post-payment FAKE source through the real archive/validation chain. No personal ledger/browser access.
import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,FLAGS} from './fixtures/c185-ended-world.mjs';
import {renewEndedDraft} from '../src/desktop/ended-draft.mjs';
import {restartExpiredPayment} from '../src/desktop/expired-payment-restart.mjs';
import {restartExpiredReview,validateExpiredReviewRestart,expiredReviewSourceShape,additionalExpiredReviewSourceShape,policyExpiredReviewSourceShape} from '../src/desktop/expired-review-restart.mjs';
import {CONTACT_SLOT_BASIS,canonicalJson,PurchaseJob} from '../web/checkout-connector/job.js';
import {PRO_PLAN,proDigest} from '../src/desktop/browser-session.mjs';
import {CHECKOUT_EXECUTOR_VERSION} from '../web/checkout-connector/page-program.js';
import {DesktopTaskStore} from '../src/desktop/task-store.mjs';
import {mkdtemp,rm,unlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,sep} from 'node:path';
import {TASK_KEY} from '../web/checkout-connector/job.js';
const OPTIONS={approved:true,newContextConfirmed:true,oldExecutorStopped:true,sameAccountOrdersClear:true,expiredCheckoutUrl:'https://secure10.www.apple.com.cn/shop/checkout'};
async function world(){
 const f=await fixture();await renewEndedDraft({...f,...FLAGS});const {w,api}=f;
 const stage=(action)=>Object.assign(w.row,{state:'NEEDS_VERIFICATION',expiresAt:0,bagAddStarted:true,resourceWritten:true,bagTotalCny:9999,pending:{id:'FAKE-pending',action,beforePhase:action==='fillDetails'?'DETAILS':'PAYMENT',...(action==='fillDetails'?{contactOnly:true}:{paymentOnly:true}),documentId:'FAKE-before',deadline:0},acceptedSlot:{date:'October 7',start:'21:15',end:'21:30',verified:true,basis:CONTACT_SLOT_BASIS},history:[{event:'slot-continued-to-contact-only-details',readSequence:1}]});
 stage('fillDetails');api.sessionId='FAKE-payment-recovery';const get=api.tabs.get,execute=api.scripting.executeScript;w.probes=0;w.expired=true;w.closed=0;
 api.executorVersion=async()=>CHECKOUT_EXECUTOR_VERSION;api.createExpiryProbe=async()=>{w.probes++;return {id:88};};
 api.tabs.get=async id=>id===88?{status:'complete',url:'https://www.apple.com.cn/shop/sorry/session_expired'}:get(id);
 api.tabs.remove=async id=>{assert.equal(id,88);w.closed++;};
 api.scripting.executeScript=async q=>q.target.tabId===88?[{frameId:0,documentId:'FAKE-expired',result:{schema:'applebuy-merchant-read/v1',phase:'UNKNOWN',path:'/shop/sorry/session_expired',verifiedStep:false,...(w.expired?{merchantError:'session-expired'}:{})}}]:execute(q);
 await restartExpiredPayment({...f,...OPTIONS});stage('continuePayment');api.sessionId='FAKE-post-review-context';w.probes=0;w.closed=0;return f;
}

async function secondWorld(){const f=await world();await restartExpiredReview({...f,...OPTIONS});Object.assign(f.w.row,{state:'NEEDS_VERIFICATION',expiresAt:0,bagAddStarted:true,resourceWritten:true,bagTotalCny:9999,pending:{id:'FAKE-generation1-payment',action:'continuePayment',beforePhase:'PAYMENT',paymentOnly:true,documentId:'FAKE-current',deadline:0},acceptedSlot:{date:'October 7',start:'21:15',end:'21:30',verified:true,basis:CONTACT_SLOT_BASIS},history:[{event:'slot-continued-to-contact-only-details',readSequence:1}]});f.api.sessionId='FAKE-one-additional-context';f.w.probes=0;return f;}

function expire(f){Object.assign(f.w.row,{state:'NEEDS_VERIFICATION',expiresAt:0,bagAddStarted:true,resourceWritten:true,bagTotalCny:9999,pending:{id:'FAKE-policy-pending',action:'continuePayment',beforePhase:'PAYMENT',paymentOnly:true,documentId:'FAKE-current',deadline:0},acceptedSlot:{date:'October 7',start:'21:15',end:'21:30',verified:true,basis:CONTACT_SLOT_BASIS},history:[{event:'slot-continued-to-contact-only-details',readSequence:1}]});f.api.sessionId='FAKE-policy-next-'+(f.w.row.desktopReviewRestart.generation+1);f.w.probes=0;}
async function policyWorld(){const f=await secondWorld();await restartExpiredReview({...f,...OPTIONS,additionalRecoveryApproved:true});expire(f);return f;}
test('C233 policy explicitly enables generation3 only after all same-cart safeguards and archives the entire source',async()=>{const f=await policyWorld(),old=structuredClone(f.w.row);assert.equal(policyExpiredReviewSourceShape(old),true);await assert.rejects(restartExpiredReview({...f,...OPTIONS,additionalRecoveryApproved:true}),/SourceUnconfirmed/);await restartExpiredReview({...f,...OPTIONS,automaticRecoveryApproved:true});const r=f.w.row;assert.equal(r.desktopReviewRestart.generation,3);assert.equal(r.desktopReviewRestart.recoveryPolicy,'confirmed-expired-prefinal/v1');assert.ok(await validateExpiredReviewRestart(r,f.api,f.store));assert.equal(canonicalJson(await f.store.readArchive(r.desktopReviewRestart.sourceArchive)),canonicalJson(old));for(const k of ['initialDates','floors','dateCursor','refusals','rejected'])assert.deepEqual(r[k],old[k]);assert.equal(r.finalIntent,null);assert.equal(r.acceptedSlot,null);assert.deepEqual(f.w.commands,[]);});
test('C233 validated policy is carried to next recovery but never substitutes fresh stop/order/expiry checks',async()=>{const f=await policyWorld();await restartExpiredReview({...f,...OPTIONS,automaticRecoveryApproved:true});expire(f);const before=canonicalJson(f.w.row);await assert.rejects(restartExpiredReview({...f,...OPTIONS,oldExecutorStopped:false}),/ApprovalRequired/);await assert.rejects(restartExpiredReview({...f,...OPTIONS,sameAccountOrdersClear:false}),/ApprovalRequired/);f.w.expired=false;await assert.rejects(restartExpiredReview({...f,...OPTIONS}),/MerchantExpiryUnconfirmed/);assert.equal(canonicalJson(f.w.row),before);f.w.expired=true;await restartExpiredReview({...f,...OPTIONS});assert.equal(f.w.row.desktopReviewRestart.generation,4);assert.ok(await validateExpiredReviewRestart(f.w.row,f.api,f.store));assert.deepEqual(f.w.commands,[]);});
for(const [name,edit]of [['current final',r=>r.finalIntent={id:'FAKE-final',sent:true}],['final history',r=>r.history.push({event:'final-unknown'})],['order reference',r=>r.orderRefHash='a'.repeat(64)],['live window',r=>r.expiresAt=Date.now()+90000],['third party flag',r=>r.desktopReviewRestart.recoveryPolicy='FAKE-policy'],['archive tampering',r=>r.desktopReviewRestart.sourceBackup.data='FAKE'],['wrong plan',r=>r.plan.product.color='FAKE other']])test('C233 '+name+' rejects before even probing the merchant',async()=>{const f=await policyWorld();edit(f.w.row);const before=canonicalJson(f.w.row);await assert.rejects(restartExpiredReview({...f,...OPTIONS,automaticRecoveryApproved:true}),/SourceUnconfirmed/);assert.equal(canonicalJson(f.w.row),before);assert.equal(f.w.probes,0);assert.deepEqual(f.w.commands,[]);});
test('C233 no boolean confirmation and a wrong singleton do not acquire reusable authority',async()=>{const f=await policyWorld();await assert.rejects(restartExpiredReview({...f,...OPTIONS,automaticRecoveryApproved:'true'}),/SourceUnconfirmed/);const before=canonicalJson(f.w.row);f.w.quantity=2;await assert.rejects(restartExpiredReview({...f,...OPTIONS,automaticRecoveryApproved:true}),/BagUnconfirmed/);assert.equal(canonicalJson(f.w.row),before);});
test('C233 policy cannot skip an ancestor or exceed bounded ancestry',async()=>{const f=await policyWorld();await restartExpiredReview({...f,...OPTIONS,automaticRecoveryApproved:true});const good=structuredClone(f.w.row);for(const edit of [r=>r.desktopReviewRestart.generation=5,r=>r.desktopReviewRestart.generation=17,r=>r.desktopReviewRestart.recoveryPolicy='FAKE',r=>delete r.desktopReviewRestart.recoveryPolicy]){const r=structuredClone(good);edit(r);assert.equal(await validateExpiredReviewRestart(r,f.api,f.store),null);}f.w.row=structuredClone(good);expire(f);f.w.row.desktopReviewRestart.generation=16;assert.equal(policyExpiredReviewSourceShape(f.w.row),false);const before=canonicalJson(f.w.row);await assert.rejects(restartExpiredReview({...f,...OPTIONS,automaticRecoveryApproved:true}),/SourceUnconfirmed/);assert.equal(canonicalJson(f.w.row),before);});
test('C233 source change or owner loss at archive cannot commit an automatic-recovery successor',async()=>{const f=await policyWorld(),before=canonicalJson(f.w.row),archive=f.store.archiveSnapshot;let live=true;f.store.archiveSnapshot=async r=>{const h=await archive(r);live=false;return h;};await assert.rejects(restartExpiredReview({...f,...OPTIONS,automaticRecoveryApproved:true,live:()=>live}),/ArchiveUnconfirmed/);assert.equal(canonicalJson(f.w.row),before);});
import {DesktopCheckoutRuntime} from '../src/desktop/checkout-runtime.mjs';
test('C233 full runtime policy recovery reuses the one bag item, one FAKE checkout and reaches REVIEW without final',async()=>{const f=await policyWorld(),runtime=new DesktopCheckoutRuntime({store:f.store,launch:async()=>({api:f.api,close:async()=>{}})});try{await runtime.open();const r=await runtime.restartPayment({...OPTIONS,automaticRecoveryApproved:true});assert.equal(r.phase,'REVIEW');assert.equal(f.w.row.desktopReviewRestart.generation,3);assert.equal(f.w.commands.filter(c=>c==='checkout').length,1);assert.equal(f.w.commands.includes('addBag'),false);assert.equal(f.w.commands.includes('submitOrder'),false);assert.equal(f.w.row.finalIntent,null);}finally{await runtime.close();}});
