import test from 'node:test';import assert from 'node:assert/strict';
import {cancelledWorld} from './fixtures/c250-cancelled-world.mjs';
import {startAfterCancelledOrder,reopenBeforeSlots,validateCancelledOrderPurchase,preSlotReopenShape} from '../src/desktop/cancelled-order-purchase.mjs';
import {canonicalJson} from '../web/checkout-connector/job.js';
import {DesktopCheckoutRuntime} from '../src/desktop/checkout-runtime.mjs';
import {PRO_PLAN,proDigest,runDesktopSession} from '../src/desktop/browser-session.mjs';
const NEW={approved:true,originalOrderAssociated:true,expectedRefHash:'a'.repeat(64)},REOPEN={approved:true,expiredCheckoutUrl:'https://secure10.www.apple.com.cn/shop/checkout'};
async function world(){const f=await cancelledWorld();await startAfterCancelledOrder({...f,...NEW});Object.assign(f.w.row,{state:'NEEDS_VERIFICATION',lastPhase:'FULFILLMENT',pending:{action:'selectPickup',beforePhase:'FULFILLMENT',id:'FAKE-pickup',deadline:0,documentId:'FAKE-original'},bagAddStarted:true,resourceWritten:true,bagTotalCny:9999,history:[]});f.api.sessionId='FAKE-reopened-early-checkout';f.w.commands=[];return f;}
test('C250 one same-cart continuation preserves the exact prior pending action and all earlier archives',async()=>{
 const f=await world(),old=structuredClone(f.w.row),before=canonicalJson(old);assert.equal(preSlotReopenShape(old),true);const r=await reopenBeforeSlots({...f,...REOPEN});assert.equal(r.created,true);assert.ok(await validateCancelledOrderPurchase(f.w.row,f.api,f.store));
 const t=f.w.row.desktopCancelledOrderPurchase;assert.equal(t.generation,2);assert.equal(t.rootPurchaseTaskId,old.taskId);assert.equal(canonicalJson(await f.store.readArchive(t.sourceArchive)),before);assert.equal(f.w.row.pending,null);assert.equal(f.w.row.finalIntent,null);assert.equal(f.w.row.acceptedSlot,null);assert.equal(f.w.row.initialDates,null);assert.equal(f.w.row.bagAddStarted,true);assert.deepEqual(f.w.commands,[]);await assert.rejects(reopenBeforeSlots({...f,...REOPEN}),/SourceUnconfirmed/);
});
for(const [name,edit,options]of [
 ['approval absent',()=>{},{approved:false}],['current final',f=>f.w.row.finalIntent={id:'FAKE-final',sent:true},{}],['current reference',f=>f.w.row.orderRefHash='c'.repeat(64),{}],['accepted slot',f=>f.w.row.acceptedSlot={date:'October 10',start:'21:15',end:'21:30',verified:true},{}],['slot list seen',f=>f.w.row.initialDates=['October 10'],{}],['slot page',f=>f.w.row.lastPhase='SLOTS',{}],['slot history',f=>f.w.row.history.push({event:'slot-attempt'}),{}],['chooseSlot pending',f=>f.w.row.pending.action='chooseSlot',{}],['action window active',f=>f.w.row.pending.deadline=Date.now()+60000,{}],['not dispatched',f=>f.w.row.pending.dispatched=false,{}],['account unknown',f=>f.api.auditOrders=async()=>({state:'unknown'}),{}],['existing unpaid',f=>f.api.auditOrders=async()=>({state:'unpaid-exists'}),{}],['no merchant expiry',f=>f.w.expired=false,{}],['empty bag',f=>f.w.phase='EMPTY_BAG',{}],['two items',f=>f.w.quantity=2,{}],['wrong price',f=>f.w.total=10000,{}],['missing host',f=>f.w.host=false,{}],['paused',()=>{},{live:()=>false}]
])test('C250 '+name+' blocks before a new task or merchant mutation',async()=>{const f=await world();edit(f);const before=canonicalJson(f.w.row),count=f.w.archives.size;await assert.rejects(reopenBeforeSlots({...f,...REOPEN,...options}));assert.equal(canonicalJson(f.w.row),before);assert.equal(f.w.archives.size,count);assert.deepEqual(f.w.commands,[]);});
test('C250 source change during bag observation cannot be overwritten',async()=>{const f=await world();f.w.onRead=()=>f.w.row.reason='FAKE-concurrent-change';await assert.rejects(reopenBeforeSlots({...f,...REOPEN}),/SourceChanged/);assert.equal(f.w.row.reason,'FAKE-concurrent-change');});
test('C250 immutable cart-only mode refuses another Add even if a mutable marker was cleared',async()=>{const f=await world();await reopenBeforeSlots({...f,...REOPEN});f.w.phase='EMPTY_BAG';f.w.row.bagAddStarted=false;const r=await runDesktopSession({store:f.store,api:f.api,tabId:7,mode:'purchase',authority:{checkoutApproved:true,newContextConfirmed:true,legacyOwnershipRevoked:true,planDigest:proDigest}});assert.match(r.reason,/same-cart-recovery-cannot-add/);assert.deepEqual(f.w.commands,[]);});
test('C250 reopening uses one fresh preflight then the production controller reaches REVIEW with zero Add',async()=>{const f=await world();let count=0;f.api.auditOrders=async()=>{count++;return{state:'clear',authenticated:true,accountHash:'b'.repeat(64),matchingCount:2};};const runtime=new DesktopCheckoutRuntime({store:f.store,ordersEnabled:true,launch:async()=>({api:f.api,close:async()=>{}})});try{await runtime.open();const r=await runtime.reopenInitial(REOPEN);assert.equal(r.phase,'REVIEW');assert.equal(count,1);assert.equal(f.w.commands.filter(x=>x==='checkout').length,1);assert.equal(f.w.commands.filter(x=>x==='addBag').length,0);}finally{await runtime.close();}});
test('C250 a sent final still queries the same order and never reuses preflight as final proof',async()=>{const f=await cancelledWorld();let lookups=0;f.api.auditOrders=async(p,ref)=>{if(ref){lookups++;return{state:'detail',sameReference:true,status:'unpaid',productMatches:true,totalCny:9999,storeMatches:true,quantity:null,slot:null};}return{state:'clear',authenticated:true,accountHash:'b'.repeat(64),matchingCount:2};};const runtime=new DesktopCheckoutRuntime({store:f.store,ordersEnabled:true,launch:async()=>({api:f.api,close:async()=>{}})});try{await runtime.open();await runtime.newPurchase(NEW);await runtime.submit({termsAccepted:true,existingOrdersChecked:true,noExtras:true});assert.equal(lookups,1);await runtime.advance({checkoutApproved:true,newContextConfirmed:true});assert.equal(lookups,2);assert.equal(f.w.commands.filter(x=>x==='submitOrder').length,1);}finally{await runtime.close();}});
test('C250 auth or unknown preflight is never cached',async()=>{for(const state of ['auth','unknown','unpaid-exists']){const f=await cancelledWorld();f.api.auditOrders=async()=>({state});const runtime=new DesktopCheckoutRuntime({store:f.store,ordersEnabled:true,launch:async()=>({api:f.api,close:async()=>{}})});try{await runtime.open();await assert.rejects(runtime.newPurchase(NEW));assert.equal(runtime.hasPreflight(f.w.row),false);assert.deepEqual(f.w.commands,[]);}finally{await runtime.close();}}});
