// Production recovery/authority, FAKE merchant/API/attestations only. No personal browser or records.
import test from 'node:test';import assert from 'node:assert/strict';
import * as cart from '../src/desktop/cart-transfer.mjs';
import {PRO_PLAN,proDigest,runDesktopSession} from '../src/desktop/browser-session.mjs';
import {createPurchaseRecord,TASK_KEY} from '../web/checkout-connector/job.js';
import {DesktopCheckoutRuntime} from '../src/desktop/checkout-runtime.mjs';
const FLAGS={approved:true,newContextConfirmed:true,merchantExpiryConfirmed:true,oldCheckoutStopped:true,sameAccountOrdersChecked:true};
async function fixture(){
 const original={...createPurchaseRecord(PRO_PLAN,{taskId:'FAKE-original',planDigest:proDigest,tabId:9,now:0,id:()=> 'FAKE'}),state:'NEEDS_VERIFICATION',bagAddStarted:true,resourceWritten:true};
 const w={row:{...structuredClone(original),reconcileOnly:true,desktopHandoff:{schema:'applebuy-desktop-handoff/v1',id:'FAKE-handoff',originalSnapshot:structuredClone(original)}},writes:0,commands:[],reads:0,phase:'BAG',quantity:1,total:9999,doc:'FAKE-bag'};
 const store={async get(){return structuredClone(w.row);},async put(k,v){assert.equal(k,TASK_KEY);w.writes++;w.row=structuredClone(v);},async acquireOwner(){return {owned:true,release:async()=>{}};}};
 const api={sessionId:'FAKE-one',tabs:{async get(){return {id:7,status:'complete',url:'https://www.apple.com.cn/shop/bag'};}},permissions:{async contains(){return true;}},scripting:{async executeScript(q){const c=q.args[1];if(c){w.commands.push(c.action);assert.equal(c.action,'checkout');w.phase='AUTH';return [{frameId:0,documentId:w.doc,result:{delivered:true}}];}w.reads++;if(w.onRead)w.onRead(w);return [{frameId:0,documentId:w.doc,result:{schema:'applebuy-merchant-read/v1',phase:w.phase,path:'/shop/bag',verifiedStep:true,purchase:{...PRO_PLAN.product,quantity:w.quantity,totalCny:w.total,itemVerified:true},extras:false}}];}}};
 for(let n=1;n<=3;n++){api.sessionId='FAKE-'+n;w.row.reconcileOnly=true;w.row.expiresAt=0;await cart.transferExistingCart({store,api,tabId:7,approved:true,newContextConfirmed:true});}
 w.row.state='NEEDS_VERIFICATION';w.row.expiresAt=0;w.row.pending={id:'FAKE-details',action:'fillDetails',documentId:'FAKE-contact',beforePhase:'DETAILS',deadline:0};w.row.acceptedSlot={date:'October 7',start:'21:15',end:'21:30',verified:true};w.row.initialDates=['October 7','October 8'];w.row.resourceWritten=true;w.row.bagAddStarted=true;w.row.reconcileOnly=true;api.sessionId='FAKE-four';w.reads=0;return {w,store,api,tabId:7};
}
const recover=f=>{assert.equal(typeof cart.transferExpiredContactOnce,'function');return cart.transferExpiredContactOnce({...f,...FLAGS});};
test('C171 ordinary fourth remains denied; exceptional contact recovery preserves every byte of the full old source',async()=>{
 const f=await fixture(),before=structuredClone(f.w.row);await assert.rejects(cart.transferExistingCart({...f,approved:true,newContextConfirmed:true}));
 await recover(f);assert.deepEqual(f.w.row.desktopTransfer.originalTask,before);assert.deepEqual(f.w.row.retiredHistory[0].desktopTransferArchive.originalSnapshot,before);assert.ok(cart.validateDesktopCartTransfer(f.w.row,f.api));assert.ok(f.w.row.acceptedSlot==null);assert.equal(f.w.row.pending,null);assert.equal(f.w.row.finalIntent,null);assert.equal(f.w.reads,2);assert.deepEqual(f.w.commands,[]);
 const r=await runDesktopSession({...f,mode:'purchase',authority:{checkoutApproved:true,newContextConfirmed:true,legacyOwnershipRevoked:true,planDigest:proDigest}});assert.equal(r.phase,'AUTH');assert.deepEqual(f.w.commands,['checkout']);assert.equal(r.realOrderVerified,false);
});
for(const name of Object.keys(FLAGS))test('C171 missing current '+name+' denies before read or write',async()=>{const f=await fixture(),before=structuredClone(f.w.row),writes=f.w.writes;assert.equal(typeof cart.transferExpiredContactOnce,'function');await assert.rejects(cart.transferExpiredContactOnce({...f,...FLAGS,[name]:false}));assert.deepEqual(f.w.row,before);assert.equal(f.w.writes,writes);assert.equal(f.w.reads,0);});
for(const [name,change] of [
 ['unknown slot instead of contact',f=>f.w.row.pending.action='chooseSlot'],
 ['active contact task window',f=>f.w.row.expiresAt=Date.now()+60000],
 ['active earlier slot deadline',f=>{f.w.row.desktopTransfer.originalTask.pending={id:'FAKE-slot',action:'chooseSlot',documentId:'FAKE-slot',deadline:Date.now()+60000};}],
 ['hidden current final',f=>f.w.row.other={finalIntent:{id:'FAKE-final',sent:true}}],
 ['archive tamper',f=>f.w.row.retiredHistory[0].extra='FAKE-tamper'],
 ['no accepted contact basis',f=>f.w.row.acceptedSlot=null],
 ['two cart items',f=>f.w.quantity=2],
 ['cart over cap',f=>f.w.total=10000],
 ['empty bag',f=>f.w.phase='EMPTY_BAG'],
 ['bag document changed',f=>f.w.onRead=w=>{if(w.reads===2)w.doc='FAKE-replaced';}],
 ['source changed during read',f=>f.w.onRead=w=>{if(w.reads===2)w.row.lastRead++;}],
])test('C171 '+name+' cannot write an exceptional successor',async()=>{const f=await fixture();change(f);const writes=f.w.writes;await assert.rejects(recover(f));assert.equal(f.w.writes,writes);assert.deepEqual(f.w.commands,[]);});
test('C171 exceptional marker cannot permit a fifth or survive fingerprint tampering',async()=>{const f=await fixture();await recover(f);f.w.row.expiresAt=0;f.w.row.reconcileOnly=true;f.api.sessionId='FAKE-five';const before=structuredClone(f.w.row),writes=f.w.writes;await assert.rejects(recover(f));await assert.rejects(cart.transferExistingCart({...f,approved:true,newContextConfirmed:true}));assert.deepEqual(f.w.row,before);assert.equal(f.w.writes,writes);f.w.row.desktopTransfer.expiredContactRecovery.sourceFingerprint='0'.repeat(64);assert.equal(cart.validateDesktopCartTransfer({...f.w.row,reconcileOnly:false},{sessionId:f.w.row.desktopContext}),null);});
test('C171 owner lost during read cannot persist an exceptional replacement',async()=>{const f=await fixture(),writes=f.w.writes;let live=true;f.w.onRead=w=>{if(w.reads===2)live=false;};await assert.rejects(cart.transferExpiredContactOnce({...f,...FLAGS,live:()=>live}));assert.equal(f.w.writes,writes);assert.deepEqual(f.w.commands,[]);});
test('C171 owned production runtime advances its real fixed store/API once; caller cannot replace those objects',async()=>{const f=await fixture();f.api.create=async()=>({id:7});let closed=false;const runtime=new DesktopCheckoutRuntime({store:f.store,launch:async()=>({api:f.api,close:async()=>{closed=true;}})});try{await runtime.open();const r=await runtime.transferContact({...FLAGS,store:{get(){throw Error('Injected store');}},api:{},tabId:999});assert.equal(r.phase,'AUTH');assert.equal(r.realOrderVerified,false);assert.deepEqual(f.w.commands,['checkout']);assert.equal(runtime.tabId,7);assert.ok(cart.validateDesktopCartTransfer(f.w.row,f.api));}finally{await runtime.close();}assert.equal(closed,true);assert.equal(runtime.cleanupConfirmed,true);});
test('C174 renewed contact attempt keeps the frozen cohort, terminal floors and refusal progress; edited replacement cannot erase them',async()=>{const f=await fixture();f.w.row.floors={'October 7':'21:15','October 8':'21:15'};f.w.row.rejected=[{date:'October 7',start:'21:15',end:'21:30',generation:1}];f.w.row.refusals=1;f.w.row.dateCursor=1;const before=structuredClone(f.w.row);await recover(f);for(const k of ['initialDates','floors','rejected','refusals','dateCursor'])assert.deepEqual(f.w.row[k],before[k]);assert.ok(cart.validateDesktopCartTransfer(f.w.row,f.api));const created=structuredClone(f.w.row);for(const mutate of [r=>r.initialDates=['October 8','October 9'],r=>r.floors={'October 7':'21:00'},r=>r.rejected=[],r=>r.refusals=0,r=>r.dateCursor=0]){const bad=structuredClone(created);mutate(bad);assert.equal(cart.validateDesktopCartTransfer(bad,f.api),null);}const grown=structuredClone(created);grown.floors['October 8']='21:30';grown.refusals=2;grown.dateCursor=2;assert.ok(cart.validateDesktopCartTransfer(grown,f.api));});
