// Exact stopped post-payment FAKE source through the real archive/validation chain. No personal ledger/browser access.
import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,FLAGS} from './fixtures/c185-ended-world.mjs';
import {renewEndedDraft} from '../src/desktop/ended-draft.mjs';
import {restartExpiredPayment} from '../src/desktop/expired-payment-restart.mjs';
import {restartExpiredReview,validateExpiredReviewRestart,expiredReviewSourceShape} from '../src/desktop/expired-review-restart.mjs';
import {CONTACT_SLOT_BASIS,canonicalJson,PurchaseJob} from '../web/checkout-connector/job.js';
import {PRO_PLAN,proDigest} from '../src/desktop/browser-session.mjs';
import {CHECKOUT_EXECUTOR_VERSION} from '../web/checkout-connector/page-program.js';
import {DesktopTaskStore} from '../src/desktop/task-store.mjs';
import {mkdtemp,rm,unlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,sep} from 'node:path';
import {TASK_KEY} from '../web/checkout-connector/job.js';
const OPTIONS={approved:true,newContextConfirmed:true,oldExecutorStopped:true,sameAccountOrdersClear:true,expiredCheckoutUrl:'https://secure10.www.apple.com.cn/shop/checkout'};
async function world(){
 const f=await fixture();await renewEndedDraft({...f,...FLAGS});const {w,api}=f;
 const stage=(action)=>Object.assign(w.row,{state:'NEEDS_VERIFICATION',expiresAt:0,bagAddStarted:true,resourceWritten:true,bagTotalCny:9999,pending:{id:'FAKE-pending',action,beforePhase:action==='fillDetails'?'DETAILS':'PAYMENT',...(action==='fillDetails'?{contactOnly:true}:{paymentOnly:true}),documentId:'FAKE-before',deadline:0},acceptedSlot:{date:'October 7',start:'21:15',end:'21:30',verified:true,basis:CONTACT_SLOT_BASIS},history:[{event:'slot-continued-to-contact-only-details',readSequence:1}]});
 stage('fillDetails');api.sessionId='FAKE-payment-recovery';const get=api.tabs.get,execute=api.scripting.executeScript;w.probes=0;w.expired=true;w.closed=0;
 api.executorVersion=async()=>CHECKOUT_EXECUTOR_VERSION;api.createExpiryProbe=async()=>{w.probes++;return {id:88};};
 api.tabs.get=async id=>id===88?{status:'complete',url:'https://www.apple.com.cn/shop/sorry/session_expired'}:get(id);
 api.tabs.remove=async id=>{assert.equal(id,88);w.closed++;};
 api.scripting.executeScript=async q=>q.target.tabId===88?[{frameId:0,documentId:'FAKE-expired',result:{schema:'applebuy-merchant-read/v1',phase:'UNKNOWN',path:'/shop/sorry/session_expired',verifiedStep:false,...(w.expired?{merchantError:'session-expired'}:{})}}]:execute(q);
 await restartExpiredPayment({...f,...OPTIONS});stage('continuePayment');api.sessionId='FAKE-post-review-context';w.probes=0;w.closed=0;return f;
}
test('C212 once-only stopped review successor archives the complete unknown source and preserves date restrictions without inheriting acceptance',async()=>{const f=await world(),old=structuredClone(f.w.row);assert.equal(expiredReviewSourceShape(old),true);const r=await restartExpiredReview({...f,...OPTIONS});assert.equal(r.created,true);const row=f.w.row;assert.ok(await validateExpiredReviewRestart(row,f.api,f.store));assert.equal(canonicalJson(await f.store.readArchive(row.desktopReviewRestart.sourceArchive)),canonicalJson(old));for(const k of ['initialDates','floors','dateCursor','refusals','rejected'])assert.deepEqual(row[k],old[k]);assert.equal(row.acceptedSlot,null);assert.equal(row.inheritedIdentity,null);assert.equal(row.reviewProgress,undefined);assert.equal(f.w.probes,1);assert.equal(f.w.closed,1);assert.deepEqual(f.w.commands,[]);await assert.rejects(restartExpiredReview({...f,...OPTIONS}),/SourceUnconfirmed/);});
for(const [name,edit]of [['current final',r=>r.finalIntent={id:'FAKE-final',sent:true}],['final history',r=>r.history.push({event:'final-unknown'})],['order reference',r=>r.orderRefHash='a'.repeat(64)],['old window active',r=>r.expiresAt=Date.now()+100000],['wrong pending',r=>r.pending.action='fillDetails'],['not dispatched',r=>r.pending.dispatched=false],['wrong floor',r=>r.floors['October 7']='21:00'],['missing contact progression',r=>r.history=[]]])test('C212 '+name+' refuses before a probe/archive/new intent',async()=>{const f=await world();edit(f.w.row);const before=canonicalJson(f.w.row),writes=f.w.writes,archives=f.w.archives.size;await assert.rejects(restartExpiredReview({...f,...OPTIONS}),/SourceUnconfirmed/);assert.equal(canonicalJson(f.w.row),before);assert.equal(f.w.writes,writes);assert.equal(f.w.archives.size,archives);assert.equal(f.w.probes,0);assert.deepEqual(f.w.commands,[]);});
for(const flag of ['approved','newContextConfirmed','oldExecutorStopped','sameAccountOrdersClear'])test('C212 missing '+flag+' cannot create a successor',async()=>{const f=await world();await assert.rejects(restartExpiredReview({...f,...OPTIONS,[flag]:false}),/ApprovalRequired/);assert.equal(f.w.probes,0);});
test('C212 absent merchant expiry leaves the old record and no new checkout',async()=>{const f=await world(),before=canonicalJson(f.w.row);f.w.expired=false;await assert.rejects(restartExpiredReview({...f,...OPTIONS}),/MerchantExpiryUnconfirmed/);assert.equal(canonicalJson(f.w.row),before);assert.equal(f.w.closed,1);assert.deepEqual(f.w.commands,[]);});
test('C212 mismatching singleton or old executor version cannot be mistaken for a safe new intent',async()=>{const f=await world(),before=canonicalJson(f.w.row);f.w.quantity=2;await assert.rejects(restartExpiredReview({...f,...OPTIONS}),/BagUnconfirmed/);assert.equal(canonicalJson(f.w.row),before);f.w.quantity=1;f.api.executorVersion=async()=> 'FAKE-old';f.w.probes=0;await assert.rejects(restartExpiredReview({...f,...OPTIONS}),/ExecutorUpdateRequired/);assert.equal(f.w.probes,0);});
test('C212 source change or ownership loss before commit cannot overwrite the retained source',async()=>{const f=await world(),archive=f.store.archiveSnapshot,before=canonicalJson(f.w.row);let live=true;f.store.archiveSnapshot=async r=>{const h=await archive(r);live=false;return h;};await assert.rejects(restartExpiredReview({...f,...OPTIONS,live:()=>live}),/ArchiveUnconfirmed/);assert.equal(canonicalJson(f.w.row),before);});
test('C212 an old unproved entry cannot consume or retire the new desktop successor',async()=>{const f=await world();await restartExpiredReview({...f,...OPTIONS});const before=canonicalJson(f.w.row),job=new PurchaseJob({store:f.store,port:{}});await assert.rejects(job.run(PRO_PLAN,{tabId:7,planDigest:proDigest}),/PermanentlyRevoked/);await assert.rejects(job.retire(),/PermanentlyRevoked/);assert.equal(canonicalJson(f.w.row),before);});
test('C212 real kernel-held atomic store preserves the full source and validates only an identical fallback backup',async()=>{const f=await world(),dir=await mkdtemp(join(tmpdir(),'applebuy-c212-')),file=join(dir,'task.json'),store=new DesktopTaskStore(file),lease=await store.acquireOwner();try{for(const old of f.w.archives.values())await store.archiveSnapshot(old);await store.put(TASK_KEY,f.w.row);const original=canonicalJson(f.w.row);await restartExpiredReview({...f,store,...OPTIONS});const row=await store.get(TASK_KEY);assert.equal(canonicalJson(await store.readArchive(row.desktopReviewRestart.sourceArchive)),original);assert.ok(await validateExpiredReviewRestart(row,f.api,store));await unlink(join(file+'.archives',row.desktopReviewRestart.sourceArchive+'.json'));assert.ok(await validateExpiredReviewRestart(row,f.api,store));row.desktopReviewRestart.sourceBackup.data='FAKE';assert.equal(await validateExpiredReviewRestart(row,f.api,store),null);}finally{await lease.release();assert.ok(resolve(dir).startsWith(resolve(tmpdir())+sep+'applebuy-c212-'));await rm(dir,{recursive:true});}});
