import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {EventEmitter} from 'node:events';
import {AuthContinuation} from '../src/desktop/auth-continuation.mjs';
const source=(await readFile(new URL('../src/desktop/native-purchase-worker.mjs',import.meta.url),'utf8')).replace(/import\s+[\s\S]*?\s+from\s+['"][^'"]+['"];?/g,'');
async function world(){
 let input,attempts=0,created=0,state='auth';const watches=[],events=[];
 class Runtime{constructor(){this.api={};this.paused=false;this.cleanupConfirmed=true;}async open(){return{legacyReadOnly:true};}async close(){}async orderAudit(){return {orderCheck:{state}};}async pause(){this.paused=true;return{readOnly:true,canContinue:false};}async reopenInitial(c){attempts++;assert.equal(c.approved,true);if(state!=='clear')throw Error('InitialCheckoutAccountUnconfirmed');created++;return{phase:'REVIEW',state:'NEEDS_USER',pendingAction:null};}}
 class Watch extends AuthContinuation{constructor(o){super({...o,setTimer:()=>1,clearTimer:()=>{}});watches.push(this);}}
 const stdin=new EventEmitter();stdin.destroy=()=>{};
 const deps={preSlotReopenShape:()=>true,createInterface:()=>{input=new EventEmitter();input.close=()=>input.emit('close');return input;},join:(...x)=>x.join('/'),DesktopCheckoutRuntime:Runtime,DesktopTaskStore:class{async get(){return{reconcileOnly:true};}},AuthContinuation:Watch,launchNativeCheckout:()=>assert.fail('No browser'),safeCheckoutDiagnostic:()=>null,stoppedCheckoutDraftSource:()=>false,TASK_KEY:'FAKE',probeCheckoutHostScope:async()=>({}),expiredPaymentSourceShape:()=>false,expiredReviewSourceShape:()=>false,additionalExpiredReviewSourceShape:()=>false,policyExpiredReviewSourceShape:()=>false,process:{argv:['node','FAKE'],cwd:()=>'/FAKE',stdout:{write:t=>events.push(JSON.parse(t))},stdin}};
 const done=new (Object.getPrototypeOf(async function(){}).constructor)(...Object.keys(deps),source)(...Object.values(deps));await new Promise(r=>setImmediate(r));
 return{events,watches,setState:s=>state=s,counts:()=>({attempts,created}),send:c=>input.listeners('line')[0](JSON.stringify(c)),close:async()=>{input.close();await done;}};
}
test('C253 recovery login automatically resumes the original explicit command once after clear account observation',async()=>{const w=await world();try{await w.send({action:'reopen-initial',approved:true,expiredCheckoutUrl:'https://secure10.www.apple.com.cn/shop/checkout'});assert.equal(w.counts().created,0);assert.notEqual(w.watches[1].timer,null);w.setState('clear');await w.watches[1].tick();assert.deepEqual(w.counts(),{attempts:2,created:1});assert.equal(w.watches[1].timer,null);await w.watches[1].tick();assert.equal(w.counts().created,1);}finally{await w.close();}});
test('C253 pause cancels login recovery and never creates an attempt afterward',async()=>{const w=await world();try{await w.send({action:'reopen-initial',approved:true});await w.send({action:'pause'});w.setState('clear');await w.watches[1].tick();assert.equal(w.counts().created,0);}finally{await w.close();}});
test('C253 an unpaid or unknown account is not treated as cleared by the recovery callback',async()=>{for(const s of ['unpaid-exists','unknown']){const w=await world();try{await w.send({action:'reopen-initial',approved:true});w.setState(s);await w.watches[1].tick();assert.equal(w.counts().created,0);}finally{await w.close();}}});
