// Physical own kernel lease/temp ledger; all values FAKE, no browser or customer ledger.
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,rm} from 'node:fs/promises';import {join,resolve,sep,basename} from 'node:path';import {tmpdir} from 'node:os';
import {acquireDesktopOwner} from '../src/desktop/owner-lease.mjs';import {TASK_KEY} from '../web/checkout-connector/job.js';
import {ownerWriteFrames,OWNER_FRAME_BYTES} from '../src/desktop/owner-write-frames.mjs';import {createHash} from 'node:crypto';
import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';import {createInterface} from 'node:readline';import {writeFile} from 'node:fs/promises';
async function clean(dir){assert.ok(resolve(dir).startsWith(resolve(tmpdir())+sep));assert.ok(basename(dir).startsWith('applebuy-FAKE-c162-'));await rm(dir,{recursive:true,force:true});}
test('C162 legitimate large full history writes losslessly under the physical owner',async()=>{const dir=await mkdtemp(join(tmpdir(),'applebuy-FAKE-c162-')),file=join(dir,'task.json'),row={schema:'FAKE-large-record',finalIntent:null,oldUnknown:{pending:'FAKE-unknown-preserved'},payload:'FAKE'.repeat(600000)};let lease;try{lease=await acquireDesktopOwner(file+'.owner');assert.equal(lease.owned,true);await lease.put(TASK_KEY,row);assert.deepEqual(JSON.parse(await readFile(file,'utf8'))[TASK_KEY],row);}finally{await lease?.release();await clean(dir);}});
test('C162 per-frame2MB survives while Unicode/surrogate and old-final fields reconstruct exactly',()=>{const row={oldFinal:{sent:true,unknown:true},text:'中文\ud800'.repeat(180000)},frames=[...ownerWriteFrames(TASK_KEY,row,4)].map(s=>{assert.ok(Buffer.byteLength(s)<=OWNER_FRAME_BYTES);return JSON.parse(s);}),begin=frames[0];assert.equal(begin.action,'putBegin');const bytes=Buffer.concat(frames.filter(f=>f.action==='putChunk').map(f=>Buffer.from(f.data,'base64')));assert.equal(bytes.length,begin.bytes);assert.equal(createHash('sha256').update(bytes).digest('hex'),begin.sha256);assert.deepEqual(JSON.parse(bytes.toString('utf8')),row);assert.equal(frames.at(-1).action,'putCommit');});
test('C162 aggregate above16MB rejects before yielding a frame',()=>{assert.throws(()=>[...ownerWriteFrames(TASK_KEY,{payload:'x'.repeat(16000001)},1)],/DesktopOwnerWriteUnconfirmed/);});
test('C162 simultaneous large and small writes are serialized and preserve the later row',async()=>{const dir=await mkdtemp(join(tmpdir(),'applebuy-FAKE-c162-')),file=join(dir,'task.json');let lease;try{lease=await acquireDesktopOwner(file+'.owner');await Promise.all([lease.put(TASK_KEY,{oldUnknown:true,payload:'FAKE'.repeat(600000)}),lease.put(TASK_KEY,{last:true,oldUnknown:true})]);assert.deepEqual(JSON.parse(await readFile(file,'utf8'))[TASK_KEY],{last:true,oldUnknown:true});}finally{await lease?.release();await clean(dir);}});
for(const end of ['EOF','release'])test('C162 actual holder '+end+' keeps an uncommitted large record off disk',async()=>{const dir=await mkdtemp(join(tmpdir(),'applebuy-FAKE-c162-')),file=join(dir,'task.json'),before=JSON.stringify({[TASK_KEY]:{unknown:true,oldFinal:{sent:true}}});let child,lines,closed;try{await writeFile(file,before);child=spawn('python',['-B',fileURLToPath(new URL('../src/desktop/owner_lease.py',import.meta.url)),file+'.owner'],{windowsHide:true,stdio:['pipe','pipe','pipe']});child.stderr.resume();closed=new Promise(r=>child.once('close',r));lines=createInterface({input:child.stdout});const first=await new Promise(r=>lines.once('line',r));assert.equal(JSON.parse(first).owned,true);const frames=[...ownerWriteFrames(TASK_KEY,{payload:'FAKE'.repeat(600000),unknown:true},3)];child.stdin.end(frames.slice(0,-1).join('')+(end==='release'?'release\n':''));assert.equal(await closed,0);assert.equal(await readFile(file,'utf8'),before);}finally{if(child&&child.exitCode===null){child.kill();await closed;}lines?.close();await clean(dir);}});
