// Explicit new-run authority only; FAKE account attestation/Chrome/site effects and ledger. Never production state.
import test from 'node:test';import assert from 'node:assert/strict';
import {restartFromCurrentEmpty,validateEmptyRestart} from '../src/desktop/empty-restart.mjs';
import {createPurchaseRecord,TASK_KEY,PurchaseJob} from '../web/checkout-connector/job.js';
import {PRO_PLAN,proDigest,runDesktopSession} from '../src/desktop/browser-session.mjs';
function fixture(){
 const original={...createPurchaseRecord(PRO_PLAN,{taskId:'FAKE-source',planDigest:proDigest,tabId:99,now:0,id:()=> 'FAKE'}),state:'NEEDS_VERIFICATION',pending:{action:'addBag',id:'FAKE-old-add',documentId:'FAKE-old-doc',deadline:0},bagAddStarted:true,resourceWritten:true};
 const w={row:{...structuredClone(original),reconcileOnly:true,desktopHandoff:{schema:'applebuy-desktop-handoff/v1',id:'FAKE-handoff',originalSnapshot:structuredClone(original)}},phase:'EMPTY_BAG',url:'https://www.apple.com.cn/shop/bag',reads:0,writes:0,commands:[],doc:'FAKE-current-empty'};
 const store={async get(){return structuredClone(w.row);},async put(k,v){assert.equal(k,TASK_KEY);w.writes++;w.row=structuredClone(v);},async acquireOwner(){return {owned:true,release:async()=>{}};}};
 const api={sessionId:'FAKE-C125-native-session',tabs:{async get(id){return {id,url:id===8?'https://www.apple.com.cn/shop/bag':w.url,status:'complete'};},async create(){return {id:8};},async remove(){},async update(id,{url}){w.url=url;w.phase='VARIANT';}},permissions:{async contains(){return true;}},scripting:{async executeScript(q){
  const c=q.args[1];if(c){w.commands.push(c.action);if(c.action==='addBag')w.phase='BAG';else if(c.action==='checkout')w.phase='AUTH';return [{frameId:0,documentId:q.target.documentIds[0],result:{delivered:true}}];}
  const side=q.target.tabId===8,phase=side?'EMPTY_BAG':w.phase;w.reads++;return [{frameId:0,documentId:side?'FAKE-side-empty':w.doc,result:{schema:'applebuy-merchant-read/v1',phase,path:side?'/shop/bag':new URL(w.url).pathname,verifiedStep:phase!=='AUTH',purchase:{...PRO_PLAN.product,quantity:1,totalCny:9999,itemVerified:true,verified:true,store:PRO_PLAN.stores[0],storeVerified:true,fulfillment:'pickup'},extras:false,variantVerified:true,quotedCny:9999,nextChoice:null}}];
 }}};return {w,store,api};
}
const consent={approved:true,accountConfirmedByUser:true,oldCheckoutStoppedByUser:true,existingOrdersCheckedByUser:true};
test('C125 explicit same-account/stopped/no-previous-order attestation plus two current empty reads creates one fresh owner without clearing unknown',async()=>{
 const f=fixture(),before=structuredClone(f.w.row);const created=await restartFromCurrentEmpty({...f,...consent,tabId:7});assert.equal(created.created,true);assert.equal(created.accountIdentityVerifiedByProgramme,false);assert.equal(f.w.reads,2);assert.equal(f.w.writes,1);assert.deepEqual(f.w.commands,[]);assert.notEqual(f.w.row.taskId,before.taskId);assert.deepEqual(f.w.row.desktopEmptyRestart.originalTask,before);assert.deepEqual(f.w.row.retiredHistory[0].desktopEmptyArchive.originalSnapshot,before);assert.equal(f.w.row.desktopEmptyRestart.originalTask.pending.action,'addBag');assert.equal(validateEmptyRestart(f.w.row,f.api).newFromEmpty,true);
 const result=await runDesktopSession({store:f.store,api:f.api,tabId:7,mode:'purchase',authority:{checkoutApproved:true,newContextConfirmed:true,legacyOwnershipRevoked:true,planDigest:proDigest}});assert.equal(result.phase,'AUTH');assert.equal(f.w.commands.filter(x=>x==='addBag').length,1);assert.equal(f.w.commands.filter(x=>x==='checkout').length,1);assert.equal(f.w.row.desktopEmptyRestart.originalTask.pending.action,'addBag');
 await assert.rejects(new PurchaseJob({store:f.store,port:{async observe(){throw Error('Original source must not observe');}}}).run(PRO_PLAN,{tabId:7,planDigest:proDigest}),/RevokedSource/);
});
test('C125 missing any current human confirmation means no read/write or native command',async()=>{
 for(const key of Object.keys(consent)){const f=fixture();await assert.rejects(restartFromCurrentEmpty({...f,...consent,[key]:false,tabId:7}));assert.equal(f.w.reads,0);assert.equal(f.w.writes,0);assert.deepEqual(f.w.commands,[]);}
 for(const bad of ['yes',1,{},null]){const f=fixture();await assert.rejects(restartFromCurrentEmpty({...f,...consent,approved:bad,tabId:7}));assert.equal(f.w.reads,0);assert.equal(f.w.writes,0);}
});
test('C125 final history, live old slot, unknown/nonempty bag and changed document cannot create new owner',async()=>{
 for(const type of ['final','slot-live','unknown','nonempty','document-changed']){const f=fixture();if(type==='final')f.w.row.desktopHandoff.originalSnapshot.finalIntent={id:'FAKE-final',sent:true};if(type==='slot-live'){f.w.row.pending={action:'chooseSlot',id:'FAKE-slot',documentId:'FAKE-old',deadline:Date.now()+100000};f.w.row.expiresAt=Date.now()+100000;}if(type==='unknown')f.w.phase='UNKNOWN';if(type==='nonempty')f.w.phase='BAG';if(type==='document-changed'){const read=f.api.scripting.executeScript;f.api.scripting.executeScript=async q=>{const out=await read(q);if(f.w.reads===2)out[0].documentId='FAKE-new-doc';return out;};}const before=structuredClone(f.w.row);await assert.rejects(restartFromCurrentEmpty({...f,...consent,tabId:7}));assert.equal(f.w.writes,0);assert.deepEqual(f.w.row,before);assert.deepEqual(f.w.commands,[]);}
});
test('C125 new context or modified source archive cannot restore purchasing; restart only reconciles and preserves source',async()=>{
 const f=fixture();await restartFromCurrentEmpty({...f,...consent,tabId:7});const before=structuredClone(f.w.row);const other={...f.api,sessionId:'FAKE-C125-other-session'};await assert.rejects(runDesktopSession({store:f.store,api:other,tabId:7,mode:'purchase',authority:{checkoutApproved:true,newContextConfirmed:true,legacyOwnershipRevoked:true,planDigest:proDigest}}));assert.deepEqual(f.w.row,before);const result=await runDesktopSession({store:f.store,api:other,tabId:7,mode:'reconcile'});assert.equal(result.realOrderVerified,false);assert.equal(f.w.row.reconcileOnly,true);assert.deepEqual(f.w.row.desktopEmptyRestart.originalTask,before.desktopEmptyRestart.originalTask);assert.deepEqual(f.w.commands,[]);
 const bad=fixture();await restartFromCurrentEmpty({...bad,...consent,tabId:7});bad.w.row.retiredHistory[0].desktopEmptyArchive.originalSnapshot.pending.id='FAKE-tampered';assert.equal(validateEmptyRestart(bad.w.row,bad.api),null);await assert.rejects(runDesktopSession({store:bad.store,api:bad.api,tabId:7,mode:'purchase',authority:{checkoutApproved:true,newContextConfirmed:true,legacyOwnershipRevoked:true,planDigest:proDigest}}));assert.deepEqual(bad.w.commands,[]);
});
