// Physical kernel/active journal/managed archive and compressed backup; FAKE source/browser/approval only.
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,rm,unlink} from 'node:fs/promises';import {resolve,join,relative} from 'node:path';import {gunzipSync,gzipSync} from 'node:zlib';
import {DesktopTaskStore} from '../src/desktop/task-store.mjs';import {validateEndedDraft} from '../src/desktop/ended-draft.mjs';
// Receive a valid generated production renewal fixture through a dedicated exported helper, no personal source.
import {endedDraftWorld} from './fixtures/c185-ended-world.mjs';
import {fixture,FLAGS} from './fixtures/c185-ended-world.mjs';import {renewEndedDraft} from '../src/desktop/ended-draft.mjs';
import {runDesktopSession,proDigest,PRO_PLAN} from '../src/desktop/browser-session.mjs';import {TASK_KEY} from '../web/checkout-connector/job.js';import {CheckoutRpcPeer} from '../web/checkout-connector/checkout-rpc-peer.js';
const parent=resolve('.local/test-runs');
test('C185 actual kernel/ledger/backup lifecycle composes with production controller to one FAKE unpaid result',async()=>{await mkdir(parent,{recursive:true});const dir=await mkdtemp(join(parent,'c185-composed-'));const store=new DesktopTaskStore(join(dir,'task.json'));let lease;try{lease=await store.acquireOwner();const f=await endedDraftWorld(store),row=await store.get(TASK_KEY);await unlink(join(dir,'task.json.archives',row.desktopEndedDraft.sourceArchive+'.json'));const scoped={get:k=>store.get(k),put:(k,v)=>store.put(k,v),readArchive:d=>store.readArchive(d),acquireOwner:async()=>({get owned(){return lease.owned;},release:async()=>{}})},authority={checkoutApproved:true,newContextConfirmed:true,legacyOwnershipRevoked:true,planDigest:proDigest};const ready=await runDesktopSession({store:scoped,api:f.api,tabId:7,mode:'purchase',authority});assert.equal(ready.phase,'REVIEW');const current=await store.get(TASK_KEY);const result=await runDesktopSession({store:scoped,api:f.api,tabId:7,mode:'purchase',authority:{...authority,finalConsent:{taskId:current.taskId,documentId:current.lastDocumentId,termsUrl:'https://www.apple.com.cn/shop/open/salespolicies',termsAccepted:true,existingOrdersChecked:true,noExtras:true,acceptedAt:Date.now()}}});assert.equal(result.state,'CONFIRMED_UNPAID');assert.equal(f.commands.filter(c=>c==='checkout').length,1);assert.equal(f.commands.filter(c=>c==='submitOrder').length,1);assert.equal(f.commands.includes('addBag'),false);}finally{await lease?.release();assert.ok(relative(parent,dir)&&!relative(parent,dir).startsWith('..'));await rm(dir,{recursive:true,force:true});}});
test('C185 owner lost after immutable archive but before active transition preserves the complete old active row',async()=>{const f=await fixture(),old=structuredClone(f.w.row),writes=f.w.writes;let live=true;const save=f.store.archiveSnapshot;f.store.archiveSnapshot=async r=>{const d=await save(r);live=false;return d;};await assert.rejects(renewEndedDraft({...f,...FLAGS,live:()=>live}));assert.deepEqual(f.w.row,old);assert.equal(f.w.writes,writes);assert.equal(f.w.archives.size,1);assert.deepEqual(f.w.commands,[]);});
for(const phase of ['EMPTY_BAG','VARIANT'])test('C185 cart-only renewal cannot configure/add when landing on '+phase,async()=>{const f=await fixture();await renewEndedDraft({...f,...FLAGS});f.w.phase=phase;const r=await runDesktopSession({...f,mode:'purchase',authority:{checkoutApproved:true,newContextConfirmed:true,legacyOwnershipRevoked:true,planDigest:proDigest}});assert.equal(r.realOrderVerified,false);assert.deepEqual(f.w.commands,[]);});
test('C185 native host coverage query accepts only the fixed declared wildcard, grants nothing',async()=>{let seen=[];const peer=new CheckoutRpcPeer({api:{permissions:{contains:async q=>{seen.push(q.origins[0]);return false;}}},contextId:'FAKE-scope-coverage',purchaseAllowed:true});assert.equal(await peer.operation('containsHost',{origins:['https://*.www.apple.com.cn/*']}),false);for(const origin of ['https://*.apple.com.cn/*','https://*/*','https://*.example.invalid/*'])await assert.rejects(peer.operation('containsHost',{origins:[origin]}));assert.deepEqual(seen,['https://*.www.apple.com.cn/*']);});
test('C185 full old source survives missing archive name in the atomic active row, and tampered backup fails',async()=>{await mkdir(parent,{recursive:true});const dir=await mkdtemp(join(parent,'c185-inline-'));const store=new DesktopTaskStore(join(dir,'task.json'));let lease;try{lease=await store.acquireOwner();const f=await endedDraftWorld(store);const row=await store.get('applebuy-single-personal-purchase/v1');const original=JSON.parse(gunzipSync(Buffer.from(row.desktopEndedDraft.sourceBackup.data,'base64')).toString('utf8'));assert.deepEqual(original,f.before);assert.ok(await validateEndedDraft(row,f.api,store));await unlink(join(dir,'task.json.archives',row.desktopEndedDraft.sourceArchive+'.json'));assert.ok(await validateEndedDraft(row,f.api,store));for(const change of [r=>delete r.desktopEndedDraft.sourceBackup,r=>r.desktopEndedDraft.sourceBackup.data='FAKE-invalid-base64',r=>r.desktopEndedDraft.sourceBackup.bytes++,r=>r.desktopEndedDraft.sourceBackup.data=gzipSync('x'.repeat(16000001)).toString('base64')]){const bad=structuredClone(row);change(bad);assert.equal(await validateEndedDraft(bad,f.api,store),null);}assert.deepEqual(f.commands,[]);}finally{await lease?.release();assert.ok(relative(parent,dir)&&!relative(parent,dir).startsWith('..'));await rm(dir,{recursive:true,force:true});}});
