// All source/accounts/merchant observations below are FAKE; original archives are compared exactly.
import test from 'node:test';import assert from 'node:assert/strict';
import {cancelledWorld} from './fixtures/c250-cancelled-world.mjs';
import {startAfterCancelledOrder,reopenBeforeSlots,restartAfterObservedRefusal,observedRefusalTrialShape,validateCancelledOrderPurchase} from '../src/desktop/cancelled-order-purchase.mjs';
import {canonicalJson} from '../web/checkout-connector/job.js';
import {DesktopCheckoutRuntime} from '../src/desktop/checkout-runtime.mjs';
const APPROVAL={approved:true,operatorObservedRefusal:true,sameAccountConfirmed:true};
async function world(){
 const f=await cancelledWorld();await startAfterCancelledOrder({...f,approved:true,originalOrderAssociated:true,expectedRefHash:'a'.repeat(64)});
 Object.assign(f.w.row,{pending:{action:'selectPickup',beforePhase:'FULFILLMENT',id:'FAKE-pickup',deadline:0,documentId:'FAKE-original'},bagAddStarted:true,resourceWritten:true,bagTotalCny:9999,lastPhase:'FULFILLMENT',history:[]});
 f.api.sessionId='FAKE-early-reopen';await reopenBeforeSlots({...f,approved:true,expiredCheckoutUrl:'https://secure10.www.apple.com.cn/shop/checkout'});
 Object.assign(f.w.row,{expiresAt:0,initialDates:['October 6','October 7','October 8'],dateCursor:0,floors:{'October 6':'21:15'},acceptedSlot:{date:'October 6',start:'21:15',end:'21:30',verified:true},finalIntent:{id:'FAKE-final',sent:true},pending:{id:'FAKE-submit',action:'submitOrder',intentId:'FAKE-final',beforePhase:'REVIEW',documentId:'FAKE-review',deadline:0},lastPhase:'SLOTS'});
 f.api.sessionId='FAKE-explicit-assisted-trial';f.w.commands=[];return f;
}
test('C254 explicit assisted trial archives the exact unknown final, preserves dates/floors, and never manufactures an automatic refusal',async()=>{const f=await world(),old=structuredClone(f.w.row);assert.equal(observedRefusalTrialShape(old),true);await restartAfterObservedRefusal({...f,...APPROVAL});const row=f.w.row,t=row.desktopCancelledOrderPurchase;assert.equal(t.generation,3);assert.equal(t.operatorObservedRefusal,true);assert.equal(row.finalRejections,undefined);assert.equal(row.finalIntent,null);assert.equal(row.pending,null);assert.deepEqual(row.initialDates,old.initialDates);assert.equal(row.dateCursor,1);assert.deepEqual(row.floors,old.floors);assert.equal(row.refusals,1);assert.equal(canonicalJson(await f.store.readArchive(t.sourceArchive)),canonicalJson(old));assert.ok(await validateCancelledOrderPurchase(row,f.api,f.store));assert.deepEqual(f.w.commands,[]);await assert.rejects(restartAfterObservedRefusal({...f,...APPROVAL}),/SourceUnconfirmed/);});
for(const [name,edit,options]of [
 ['no new authorization',()=>{},{approved:false}],['operator did not witness refusal',()=>{},{operatorObservedRefusal:false}],['different account not confirmed',()=>{},{sameAccountConfirmed:false}],['window still active',f=>f.w.row.expiresAt=Date.now()+60000,{}],['receipt already found',f=>f.w.row.orderRefHash='c'.repeat(64),{}],['final not sent',f=>f.w.row.finalIntent.sent=false,{}],['third date exhausted',f=>{f.w.row.initialDates=['October 6'];},{}],['unknown account',f=>f.api.auditOrders=async()=>({state:'unknown'}),{}],['active unpaid order',f=>f.api.auditOrders=async()=>({state:'unpaid-exists'}),{}],['empty bag',f=>f.w.phase='EMPTY_BAG',{}],['two items',f=>f.w.quantity=2,{}],['wrong total',f=>f.w.total=10000,{}],['same live context',f=>f.api.sessionId=f.w.row.desktopContext,{}],['lost owner',()=>{},{live:()=>false}]
])test('C254 '+name+' preserves source and sends no merchant action',async()=>{const f=await world();edit(f);const before=canonicalJson(f.w.row),n=f.w.archives.size;await assert.rejects(restartAfterObservedRefusal({...f,...APPROVAL,...options}));assert.equal(canonicalJson(f.w.row),before);assert.equal(f.w.archives.size,n);assert.deepEqual(f.w.commands,[]);});
test('C254 a concurrent source change is never overwritten',async()=>{const f=await world();f.w.onRead=()=>f.w.row.reason='FAKE-intervening-change';await assert.rejects(restartAfterObservedRefusal({...f,...APPROVAL}),/SourceChanged/);assert.equal(f.w.row.reason,'FAKE-intervening-change');});
test('C254 real runtime drives the next original terminal to REVIEW with zero Add and no new final',async()=>{const f=await world();let checks=0;f.api.auditOrders=async()=>{checks++;return {state:'clear',authenticated:true,accountHash:'b'.repeat(64),matchingCount:3};};const r=new DesktopCheckoutRuntime({store:f.store,ordersEnabled:true,launch:async()=>({api:f.api,close:async()=>{}})});try{await r.open();const result=await r.restartObservedRefusal(APPROVAL);assert.equal(result.phase,'REVIEW',result.reason);assert.equal(checks,1);assert.equal(f.w.slot.date,'October 7');assert.equal(f.w.commands.filter(x=>x==='checkout').length,1);assert.equal(f.w.commands.includes('addBag'),false);assert.equal(f.w.commands.includes('submitOrder'),false);}finally{await r.close();}});
