// FAKE sources and merchant responses; no personal journal or browser access.
import test from 'node:test';import assert from 'node:assert/strict';
import {cancelledWorld} from './fixtures/c250-cancelled-world.mjs';
import {startAfterCancelledOrder,reopenBeforeSlots,restartAfterObservedRefusal,restartExpiredPreparedReview,expiredPreparedTrialShape,validateCancelledOrderPurchase} from '../src/desktop/cancelled-order-purchase.mjs';
import {canonicalJson} from '../web/checkout-connector/job.js';import {DesktopCheckoutRuntime} from '../src/desktop/checkout-runtime.mjs';
const OPTIONS={approved:true,merchantExpiryConfirmed:true,sameAccountConfirmed:true};
async function world(){
 const f=await cancelledWorld();await startAfterCancelledOrder({...f,approved:true,originalOrderAssociated:true,expectedRefHash:'a'.repeat(64)});
 Object.assign(f.w.row,{pending:{action:'selectPickup',beforePhase:'FULFILLMENT',id:'FAKE-pickup',deadline:0,documentId:'FAKE-original'},bagAddStarted:true,resourceWritten:true,bagTotalCny:9999,lastPhase:'FULFILLMENT',history:[]});
 f.api.sessionId='FAKE-reopen';await reopenBeforeSlots({...f,approved:true,expiredCheckoutUrl:'https://secure10.www.apple.com.cn/shop/checkout'});
 Object.assign(f.w.row,{expiresAt:0,initialDates:['October 6','October 7','October 8'],dateCursor:0,floors:{'October 6':'21:15'},acceptedSlot:{date:'October 6',start:'21:15',end:'21:30',verified:true},finalIntent:{id:'FAKE-final',sent:true},pending:{id:'FAKE-submit',action:'submitOrder',intentId:'FAKE-final',beforePhase:'REVIEW',documentId:'FAKE-review',deadline:0},lastPhase:'SLOTS'});
 f.api.sessionId='FAKE-assisted';await restartAfterObservedRefusal({...f,approved:true,operatorObservedRefusal:true,sameAccountConfirmed:true});
 Object.assign(f.w.row,{expiresAt:0,lastPhase:'REVIEW',acceptedSlot:{date:'October 7',start:'21:15',end:'21:30',verified:true},reviewProgress:{kind:'native-controlled-review-progression/v1',id:'FAKE-ready',store:'Apple 大连恒隆广场',date:'October 7',start:'21:15',end:'21:30',totalCny:9999}});f.w.row.floors['October 7']='21:15';
 f.api.sessionId='FAKE-refreshed-before-final';f.w.commands=[];return f;
}
test('C255 only the expired never-submitted review renews; source and exact date cursor/floors/refusals stay intact',async()=>{const f=await world(),old=structuredClone(f.w.row);assert.equal(expiredPreparedTrialShape(old),true);await restartExpiredPreparedReview({...f,...OPTIONS});const row=f.w.row;assert.equal(row.desktopCancelledOrderPurchase.generation,4);assert.equal(row.dateCursor,old.dateCursor);assert.equal(row.refusals,old.refusals);assert.deepEqual(row.initialDates,old.initialDates);assert.deepEqual(row.floors,old.floors);assert.equal(canonicalJson(await f.store.readArchive(row.desktopCancelledOrderPurchase.sourceArchive)),canonicalJson(old));assert.equal(row.finalIntent,null);assert.ok(await validateCancelledOrderPurchase(row,f.api,f.store));assert.deepEqual(f.w.commands,[]);await assert.rejects(restartExpiredPreparedReview({...f,...OPTIONS}));});
for(const [name,edit,options]of [
 ['not approved',()=>{},{approved:false}],['expiry not observed',()=>{},{merchantExpiryConfirmed:false}],['account not confirmed',()=>{},{sameAccountConfirmed:false}],['active window',f=>f.w.row.expiresAt=Date.now()+60000,{}],['pending final',f=>{f.w.row.finalIntent={id:'FAKE-sent',sent:true};f.w.row.pending={id:'FAKE-pending',action:'submitOrder',documentId:'FAKE',deadline:0};},{}],['unsent final intent',f=>f.w.row.finalIntent={id:'FAKE-draft',sent:false},{}],['pending payment',f=>f.w.row.pending={id:'FAKE-payment',action:'continuePayment',documentId:'FAKE',deadline:0},{}],['receipt',f=>f.w.row.orderRefHash='c'.repeat(64),{}],['no prepared review',f=>f.w.row.reviewProgress=null,{}],['changed slot',f=>f.w.row.reviewProgress.date='October 8',{}],['unknown account',f=>f.api.auditOrders=async()=>({state:'unknown'}),{}],['existing unpaid',f=>f.api.auditOrders=async()=>({state:'unpaid-exists'}),{}],['two items',f=>f.w.quantity=2,{}],['empty cart',f=>f.w.phase='EMPTY_BAG',{}],['lost owner',()=>{},{live:()=>false}]
])test('C255 '+name+' prevents a new attempt and leaves the source unchanged',async()=>{const f=await world();edit(f);const before=canonicalJson(f.w.row),n=f.w.archives.size;await assert.rejects(restartExpiredPreparedReview({...f,...OPTIONS,...options}));assert.equal(canonicalJson(f.w.row),before);assert.equal(f.w.archives.size,n);assert.deepEqual(f.w.commands,[]);});
test('C255 readonly observation of the expired source does not erase prepared-review proof or lift that source',async()=>{const f=await world();f.w.row.reconcileOnly=true;f.w.row.lastPhase='BAG';const old=structuredClone(f.w.row);await restartExpiredPreparedReview({...f,...OPTIONS});assert.equal((await f.store.readArchive(f.w.row.desktopCancelledOrderPurchase.sourceArchive)).reconcileOnly,true);assert.equal(old.finalIntent,null);assert.notEqual(f.w.row.taskId,old.taskId);});
test('C255 runtime reaches fresh REVIEW on the same original day with zero Add/final',async()=>{const f=await world();const runtime=new DesktopCheckoutRuntime({store:f.store,ordersEnabled:true,launch:async()=>({api:f.api,close:async()=>{}})});try{await runtime.open();const r=await runtime.restartObservedRefusal({...OPTIONS,preparedReviewExpired:true});assert.equal(r.phase,'REVIEW',r.reason);assert.equal(f.w.slot.date,'October 7');assert.equal(f.w.commands.filter(x=>x==='checkout').length,1);assert.equal(f.w.commands.includes('addBag'),false);assert.equal(f.w.commands.includes('submitOrder'),false);}finally{await runtime.close();}});
