import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {EventEmitter} from 'node:events';
import {StartApproval,START_TERMS} from '../src/desktop/start-approval.mjs';import {proDigest} from '../src/desktop/browser-session.mjs';
const row=()=>({taskId:'FAKE-C257-task',planDigest:proDigest,expiresAt:Date.now()+60000,lastDocumentId:'FAKE-review',lastPhase:'REVIEW'});
const review=r=>({taskId:r.taskId,documentId:r.lastDocumentId,termsUrl:START_TERMS,totalCny:9999});
test('C257 displayed Start agreement consumes only once for the same unchanged task',()=>{const r=row(),a=new StartApproval();a.bind(r,START_TERMS);assert.equal(a.consume(r,review(r)),true);a.bind(r,START_TERMS);assert.equal(a.consume(r,review(r)),false);});
for(const field of ['finalIntent','pending','finalRejections','reconcileOnly','expiresAt','planDigest'])test('C257 start refuses '+field+' unsafe source',()=>{const r={...row(),[field]:{finalIntent:{sent:true},pending:{action:'submitOrder'},finalRejections:[{fake:true}],reconcileOnly:true,expiresAt:0,planDigest:'FAKE-wrong'}[field]},a=new StartApproval();a.bind(r,START_TERMS);assert.equal(a.consume(r,review(r)),false);});
test('C257 changed terms/price/document/deadline cannot consume original consent; pause clears it',()=>{for(const delta of [{termsUrl:'https://evil.invalid'},{totalCny:10000},{documentId:'other'},{taskId:'other'}]){const r=row(),a=new StartApproval();a.bind(r,START_TERMS);assert.equal(a.consume(r,{...review(r),...delta}),false);}const r=row(),a=new StartApproval();a.bind(r,START_TERMS);assert.equal(a.consume({...r,expiresAt:r.expiresAt+1},review(r)),false);a.clear();assert.equal(a.consume(r,review(r)),false);});
const source=(await readFile(new URL('../src/desktop/native-purchase-worker.mjs',import.meta.url),'utf8')).replace(/import\s+[\s\S]*?\s+from\s+['"][^'"]+['"];?/g,'');
async function worker({unknown=false}={}){
 let input,submits=0,configs=[],r=row();if(unknown){r.finalIntent={sent:true};r.pending={action:'submitOrder'};}
 const events=[];class Runtime{
  constructor(){this.paused=false;this.cleanupConfirmed=true;this.api={configureLogin:async c=>{configs.push(c);return{state:'configured'};}};}
  track(fn){return fn();}async open(){return{};}async close(){}async advance(){this.finalDescriptor=review(r);return{state:'NEEDS_USER',phase:'REVIEW'};}
  async submit(c){assert.deepEqual(c,{termsAccepted:true,existingOrdersChecked:true,noExtras:true});submits++;r.finalIntent={sent:true};r.pending={action:'submitOrder'};this.finalDescriptor=null;return{state:'NEEDS_VERIFICATION',phase:'UNKNOWN',pendingAction:'submitOrder'};}
  async pause(){this.paused=true;return{};}
 }
 const stdin=new EventEmitter();stdin.destroy=()=>{};
 const deps={StartApproval,preSlotReopenShape:()=>false,createInterface:()=>{input=new EventEmitter();input.close=()=>input.emit('close');return input;},join:(...x)=>x.join('/'),DesktopCheckoutRuntime:Runtime,DesktopTaskStore:class{async get(){return r;}},AuthContinuation:class{reading=false;stop(){}start(){}},launchNativeCheckout:()=>assert.fail('No browser'),safeCheckoutDiagnostic:()=>null,stoppedCheckoutDraftSource:()=>false,TASK_KEY:'FAKE',probeCheckoutHostScope:async()=>({}),expiredPaymentSourceShape:()=>false,expiredReviewSourceShape:()=>false,additionalExpiredReviewSourceShape:()=>false,policyExpiredReviewSourceShape:()=>false,process:{argv:['node','FAKE'],cwd:()=>'/FAKE',stdout:{write:t=>events.push(JSON.parse(t))},stdin}};
 const done=new(Object.getPrototypeOf(async function(){}).constructor)(...Object.keys(deps),source)(...Object.values(deps));await new Promise(r=>setImmediate(r));
 return{events,configs,send:c=>input.listeners('line')[0](JSON.stringify(c)),count:()=>submits,close:async()=>{input.close();await done;}};
}
test('C257 real worker composition submits once from scoped Start, strips login from events and clears on pause',async()=>{const w=await worker();try{await w.send({action:'advance',checkoutApproved:true,newContextConfirmed:true,startTermsUrl:START_TERMS,privateLogin:{account:'fake@example.invalid',password:'FAKE257-private'}});assert.equal(w.count(),1);assert.equal(JSON.stringify(w.events).includes('FAKE257-private'),false);assert.equal(JSON.stringify(w.events).includes('fake@example.invalid'),false);await w.send({action:'advance',checkoutApproved:true,newContextConfirmed:true,startTermsUrl:START_TERMS});assert.equal(w.count(),1);await w.send({action:'pause'});assert.equal(w.configs.at(-1),null);}finally{await w.close();}});
test('C257 existing unknown submission never auto-submits even with a new Start click',async()=>{const w=await worker({unknown:true});try{await w.send({action:'advance',checkoutApproved:true,newContextConfirmed:true,startTermsUrl:START_TERMS});assert.equal(w.count(),0);}finally{await w.close();}});
